var ryzomLabels=[
{x:18810,y:-24373,type:6, level:0, icon:"", name:{en:"Cheapside Market",fr:"Marché des Bonnes Affaires",de:"Fremdenbasar",ru:"Рынок Чипсайд "}},
{x:18891,y:-24346,type:6, level:0, icon:"", name:{en:"Cerakos Gate",fr:"Porte de Cerakos",de:"Cerakos-Tor",ru:"Врата Церакос"}},
{x:18673,y:-24414,type:6, level:0, icon:"", name:{en:"Highmarket",fr:"Grand Marché",de:"Kalus-Basar",ru:"Большой Базар"}},
{x:18566,y:-24448,type:6, level:0, icon:"", name:{en:"Academy Place",fr:"Place des Académies",de:"Platz der Akademie",ru:"Военная Академия"}},
{x:18688,y:-24503,type:6, level:0, icon:"", name:{en:"Oasis Fountain Square",fr:"Carré à la Fontaine",de:"Brunnenplatz",ru:"Площадь Фонтана Оазиса"}},
{x:18624,y:-24505,type:6, level:0, icon:"", name:{en:"Guardhouse Place",fr:"Place des Corps de Garde",de:"Turm der Schildwacht",ru:"Городсткие Казармы"}},
{x:18489,y:-24439,type:6, level:0, icon:"", name:{en:"Imperial Hall Square",fr:"Square Impérial",de:"Platz der Imperialen Halle",ru:"Площадь Имперских Залов"}},
{x:18511,y:-24574,type:6, level:0, icon:"", name:{en:"Karavia Square",fr:"Square de Karavia",de:"Karavia-Platz",ru:"Площадь Каравии"}},
{x:18444,y:-24515,type:6, level:0, icon:"", name:{en:"Agora",fr:"Agora",de:"Agora",ru:"Агора"}},
{x:18569,y:-24617,type:6, level:0, icon:"", name:{en:"Forge",fr:"Forge",de:"Schmiede",ru:"Кузня"}},
{x:18729,y:-24382,type:6, level:0, icon:"", name:{en:"Market Lane",fr:"Ruelle des Marchands",de:"Marktgasse",ru:"Рыночный пееулок"}},
{x:18744,y:-24431,type:6, level:0, icon:"", name:{en:"Cheapside Way",fr:"Chemin des Bonnes Affaires",de:"Basarstraße",ru:"Улица Чипсайд "}},
{x:18609,y:-24408,type:6, level:0, icon:"", name:{en:"Trader&#039;s Way",fr:"Chemin des Négoces",de:"Händlergasse",ru:"Улица Торговцев"}},
{x:18614,y:-24447,type:6, level:0, icon:"", name:{en:"Pyr High Street",fr:"Grande Rue de Pyr",de:"Pyr-Hochstraße",ru:"Улица Высоты Пира"}},
{x:18571,y:-24381,type:6, level:0, icon:"", name:{en:"Northgate Road",fr:"Route du Nord",de:"Nordtorstraße",ru:"Путь Северных Врат"}},
{x:18862,y:-24441,type:6, level:0, icon:"", name:{en:"Cerakos Avenue",fr:"Avenue Cerakos",de:"Cerakos-Allee",ru:"Церакос авеню"}},
{x:18872,y:-24459,type:6, level:0, icon:"", name:{en:"Arispotle Avenue",fr:"Avenue Arispotle",de:"Arispotle-Allee",ru:"Ариспотл авеню"}},
{x:18808,y:-24509,type:6, level:0, icon:"", name:{en:"Coriolis Circus",fr:"Cirque de Coriolis",de:"Coriolis-Ring",ru:"Круг Кориолиса"}},
{x:18766,y:-24511,type:6, level:0, icon:"", name:{en:"Rydon&#039;s Walk",fr:"Promenade de Rydon",de:"Rydon-Weg",ru:"Переулок Райдона"}},
{x:18724,y:-24490,type:6, level:0, icon:"", name:{en:"Central Lane",fr:"Ruelle du Centre",de:"Zentralweg",ru:"Улица Центральная"}},
{x:18654,y:-24485,type:6, level:0, icon:"", name:{en:"Leanon Street",fr:"Rue Leanon",de:"Leanon-Straße",ru:"Улица Леанон"}},
{x:18654,y:-24526,type:6, level:0, icon:"", name:{en:"Dexton Street",fr:"Rue Dexton",de:"Dexton-Straße",ru:"Улица Декстона"}},
{x:18597,y:-24504,type:6, level:0, icon:"", name:{en:"Guardhouse Way",fr:"Chemin des Corps de Garde",de:"Weg der Schildwacht",ru:"Казарменный переулок"}},
{x:18580,y:-24538,type:6, level:0, icon:"", name:{en:"Upper Piros Street",fr:"Rue du Haut-Piros",de:"Obere Piros-Straße",ru:"Улица Верхний Пайрос"}},
{x:18561,y:-24557,type:6, level:0, icon:"", name:{en:"Karavia Road",fr:"Route de Karavia",de:"Karavia-Straße",ru:"Каравия авеню"}},
{x:18596,y:-24601,type:6, level:0, icon:"", name:{en:"Forge and Hammer Way",fr:"Route de la Forge et du Marteau",de:"Weg von Hammer und Schmiede",ru:"Переулок Молота и Наковальни"}},
{x:18618,y:-24575,type:6, level:0, icon:"", name:{en:"Lower Piros Street",fr:"Rue du Bas-Piros",de:"Untere Piros-Straße",ru:"Улица Нижний Пайрос"}},
{x:18684,y:-24583,type:6, level:0, icon:"", name:{en:"Southgate Road",fr:"Route du Sud",de:"Südtorstraße",ru:"Путь Южных врат"}},
{x:18669,y:-24548,type:6, level:0, icon:"", name:{en:"Bath Lane",fr:"Chemin de la Cuvette",de:"Badegasse",ru:"Улица Терм"}},
{x:18702,y:-24560,type:6, level:0, icon:"", name:{en:"Abylus Circus",fr:"Cirque d&#039;Abylus",de:"Abylus-Ring",ru:"Круг Абилуса"}},
{x:18711,y:-24524,type:6, level:0, icon:"", name:{en:"Fountain Road",fr:"Route à la Fontaine",de:"Quellweg",ru:"Улица Фонтанов"}},
{x:18741,y:-24555,type:6, level:0, icon:"", name:{en:"Miners&#039; Row",fr:"Venelle des Mineurs",de:"Bergarbeiterviertel",ru:"Шахтерские ряды"}},
{x:18729,y:-24468,type:6, level:0, icon:"", name:{en:"Merchant&#039;s Walk",fr:"Promenade des Marchands",de:"Kaufmannsgasse",ru:"Купеческий переулок"}},
{x:4720,y:-3282,type:6, level:0, icon:"", name:{en:"Zachini Ward",fr:"District de Zachini",de:"Zachini-Bezirk",ru:"Округ Зачини"}},
{x:4720,y:-3418,type:6, level:0, icon:"", name:{en:"Yasson Ward",fr:"District de Yasson",de:"Yasson-Bezirk",ru:"Округ Яссон"}},
{x:4718,y:-3536,type:6, level:0, icon:"", name:{en:"Aniro Ward",fr:"District d&#039;Aniro",de:"Aniro-Bezirk",ru:"Округ Аниро"}},
{x:4751,y:-3635,type:6, level:0, icon:"", name:{en:"Tylini Ward",fr:"District de Tylini",de:"Tylini-Bezirk",ru:"Округ Тайлини"}},
{x:4677,y:-3637,type:6, level:0, icon:"", name:{en:"Libia Ward",fr:"District de Libia",de:"Libia-Bezirk",ru:"Округ Либия"}},
{x:17169,y:-32928,type:6, level:0, icon:"", name:{en:"Fairmarket Fork",fr:"Fourche du Bon Marché",de:"Fairhaven Trödelmarkt",ru:"Развилка Фэйрмаркет"}},
{x:17106,y:-32777,type:6, level:0, icon:"", name:{en:"Land&#039;s End",fr:"Bout des Terres",de:"Landende",ru:"Край Света"}},
{x:17028,y:-32965,type:6, level:0, icon:"", name:{en:"Windy Head",fr:"Façade des Vents",de:"Umwehte Höhe",ru:"Ветреные головы"}},
{x:17107,y:-33094,type:6, level:0, icon:"", name:{en:"Hartley Point",fr:"Hartley Point",de:"Hartley-Aussichtspunkt",ru:"Хартли Поинт"}},
{x:17236,y:-33001,type:6, level:0, icon:"", name:{en:"Council Chamber Square",fr:"Square de la Chambre du Conseil",de:"Ratskammerplatz",ru:"Площадь Палат Совета"}},
{x:17334,y:-32974,type:6, level:0, icon:"", name:{en:"Eastmarket",fr:"Marché Est",de:"Ostmarkt",ru:"Восточный Рынок"}},
{x:17302,y:-33068,type:6, level:0, icon:"", name:{en:"Frogmore Place",fr:"Place Frogmore",de:"Frogmore-Platz",ru:"Площадь Лягушек"}},
{x:17270,y:-33202,type:6, level:0, icon:"", name:{en:"Loria&#039;s Rise",fr:"Côte de Loria",de:"Lorias Aufstieg",ru:"Возвышение Лории"}},
{x:17100,y:-32945,type:6, level:0, icon:"", name:{en:"Rigan Road",fr:"Route de Rigan",de:"Rigan-Strasse",ru:"Риган Роуд"}},
{x:17154,y:-32850,type:6, level:0, icon:"", name:{en:"Bell Lane",fr:"Chemin du Clocher",de:"Glockengasse",ru:"Колокольная Улица"}},
{x:17200,y:-32962,type:6, level:0, icon:"", name:{en:"Upper Chamber Avenue",fr:"Avenue de la Chambre Haute",de:"Obere Ratsstraße",ru:"Авеню Верхних палат"}},
{x:17272,y:-33035,type:6, level:0, icon:"", name:{en:"Lower Chamber Avenue",fr:"Avenue de la Chambre Basse",de:"Untere Ratsstraße",ru:"Авеню Нижних палат"}},
{x:17162,y:-33033,type:6, level:0, icon:"", name:{en:"Hartley&#039;s Way",fr:"Chemin de Hartley",de:"Hartley-Weg",ru:"Проулок Хартли "}},
{x:17284,y:-32984,type:6, level:0, icon:"", name:{en:"Eastmarket Walk",fr:"Promenade du Marché Est",de:"Ostmarkt-Gang",ru:"Переулок Восточного Рынка"}},
{x:17317,y:-33021,type:6, level:0, icon:"", name:{en:"Hobelen Walk",fr:"Promenade d&#039;Hobelen",de:"Hobelen-Gang",ru:"Переулок Гобеленов"}},
{x:17287,y:-33134,type:6, level:0, icon:"", name:{en:"Frogmore Lane",fr:"Chemin de Frogmore",de:"Frogmore-Weg",ru:"Лягушачья улица"}},
{x:8801,y:-2957,type:6, level:0, icon:"", name:{en:"Cemetery District",fr:"Cimetière",de:"Friedhof",ru:"Кладбищенский Район"}},
{x:8737,y:-2942,type:6, level:0, icon:"", name:{en:"Goo Chase District",fr:"District de Goo Chase",de:"Goo-Chase-Distrikt",ru:"Район Изгнания Гуу"}},
{x:8662,y:-2945,type:6, level:0, icon:"", name:{en:"Highmart District",fr:"Highmart",de:"Vorderer Markt",ru:"Район Большого Базара"}},
{x:8667,y:-2836,type:6, level:0, icon:"", name:{en:"Temple Hall District",fr:"District de Temple Hall",de:"Tempelhallen-Distrikt",ru:"Район Храмовых залов"}},
{x:8564,y:-2933,type:6, level:0, icon:"", name:{en:"West Hollow District",fr:"District de West Hollow",de:"West-Hollow-Distrikt",ru:"Район Чистого колодца"}},
{x:8712,y:-2783,type:6, level:0, icon:"", name:{en:"Daïsha Estate",fr:"Domaine de Daïsha",de:"Daïsha-Viertel",ru:"Имение Даиши"}},
{x:8567,y:-2798,type:6, level:0, icon:"", name:{en:"Win-Cho Estate",fr:"Domaine de Win-Cho",de:"Win-Cho-Viertel",ru:"Имение Вин-Чо"}},
{x:1365,y:-10167,type:5, level:0, icon:"", name:{en:"Hallowed Mountain",fr:"Montagne Sacrée",de:"Heiliger Berg",ru:"Священная Гора"}},
{x:1041,y:-10478,type:5, level:0, icon:"", name:{en:"Saprun Watch",fr:"Guet de la Montée de Sève",de:"Sapquellen-Wacht",ru:"Дозор Потока сэп"}},
{x:1359,y:-10720,type:5, level:0, icon:"", name:{en:"Templedoom",fr:"Temple Maudit",de:"Tempel der Verdammnis",ru:"Храм Обреченных"}},
{x:19099,y:-24020,type:5, level:0, icon:"", name:{en:"Valley of Emperors",fr:"Vallée des Empereurs",de:"Herrscherebene",ru:"Долина Императоров"}},
{x:18180,y:-24689,type:5, level:0, icon:"", name:{en:"Fourways",fr:"Quatre Chemins",de:"Vier Wege",ru:"Четырепутье"}},
{x:18458,y:-25079,type:5, level:0, icon:"", name:{en:"Canyon Pass",fr:"Col aux Canyons",de:"Schluchtenpass",ru:"Горловина Каньона"}},
{x:17582,y:-25006,type:5, level:0, icon:"", name:{en:"Oasis Rift",fr:"Crevasse des Oasis",de:"Oasenspalte",ru:"Разлом Оазиса"}},
{x:17820,y:-24850,type:5, level:0, icon:"", name:{en:"Clopper Hill",fr:"Colline des Cloppers",de:"Clopperhügel",ru:"Холм Клопперов"}},
{x:17753,y:-25041,type:5, level:0, icon:"", name:{en:"Midpeaks",fr:"Pics du Milieu",de:"Mittlere Gipfel",ru:"Средигорье"}},
{x:18046,y:-24853,type:5, level:0, icon:"", name:{en:"Barkgully",fr:"Couloir aux Ecorces",de:"Rindenriss",ru:"Корковражье"}},
{x:17905,y:-25462,type:5, level:0, icon:"", name:{en:"Route of the Flaming Forest",fr:"Route de la Forêt Enflammée",de:"Weg des verbrannten Waldes",ru:"Путь в пылающий лес"}},
{x:17358,y:-24701,type:5, level:0, icon:"", name:{en:"Lonesome Pass",fr:"Col de la Solitude",de:"Einsamer Pass",ru:"Дорога Одиночества"}},
{x:17281,y:-25785,type:5, level:0, icon:"", name:{en:"The Vast Expanse",fr:"Vaste Etendue",de:"Die enorme Weite",ru:"Широкие просторы"}},
{x:16877,y:-25704,type:5, level:0, icon:"", name:{en:"Hightowers",fr:"Hautes Tours",de:"Hochtürme",ru:"Высокие Башни"}},
{x:19276,y:-25596,type:5, level:0, icon:"", name:{en:"The Waste",fr:"Terres Désolées",de:"Der Untergang",ru:"Пустошь"}},
{x:19554,y:-25540,type:5, level:0, icon:"", name:{en:"Highridges",fr:"Hauts Récifs",de:"Hohes Riff",ru:"Вышние Хребты"}},
{x:20160,y:-25123,type:5, level:0, icon:"", name:{en:"Barker Dunes",fr:"Dunes de Barker",de:"Rindendünen",ru:"Дюны Искусников"}},
{x:19929,y:-25537,type:5, level:0, icon:"", name:{en:"Varynx Rise",fr:"Côte des Varinx",de:"Varinx-Hänge",ru:"Возвышение Варинксов"}},
{x:19809,y:-25297,type:5, level:0, icon:"", name:{en:"Troubled Water",fr:"Eaux Tourmentées",de:"Wildes Wasser",ru:"Неспокойные воды"}},
{x:16475,y:-24407,type:5, level:0, icon:"", name:{en:"Dyron Hill",fr:"Colline de Dyron",de:"Dyron-Anhöhe",ru:"Холм Дайрона"}},
{x:16269,y:-25058,type:5, level:0, icon:"", name:{en:"Dragon&#039;s Tail",fr:"Queue du Dragon",de:"Drachenschwanz",ru:"Хвост Дракона"}},
{x:16578,y:-25176,type:5, level:0, icon:"", name:{en:"Malmont",fr:"Malmontagne",de:"Malmont",ru:"Мальмонт"}},
{x:16725,y:-25190,type:5, level:0, icon:"", name:{en:"Ruins of Mossok",fr:"Ruines de Mossok",de:"Ruinen von Mossok",ru:"Руины Моссока"}},
{x:18414,y:-26519,type:5, level:0, icon:"", name:{en:"Ash Gorge",fr:"Gorge des Cendres",de:"Schlucht der Asche",ru:"Пепельная Пасть"}},
{x:18794,y:-26399,type:5, level:0, icon:"", name:{en:"Thesos Springs",fr:"Sources de Thesos",de:"Thesos-Quelle",ru:"Источники Фессоса"}},
{x:19100,y:-26487,type:5, level:0, icon:"", name:{en:"Thesos Billabong",fr:"Mare de Thesos",de:"Thesos-Flussbett",ru:"Заводи Фессоса"}},
{x:19225,y:-26668,type:5, level:0, icon:"", name:{en:"South Range",fr:"Chaîne Sud",de:"Südliche Hügelkette",ru:"Южная Цепь"}},
{x:19561,y:-26434,type:5, level:0, icon:"", name:{en:"Thesos Falls Tor",fr:"Butte des Chutes de Thesos",de:"Thesos-Wasserfallpforte",ru:"Скала Водопада Фессоса"}},
{x:20128,y:-26885,type:5, level:0, icon:"", name:{en:"Kipucka Plain",fr:"Plaine des Kipuckas",de:"Kipucka-Ebene",ru:"Равнина Кипакки"}},
{x:19224,y:-25282,type:5, level:0, icon:"", name:{en:"Dragon&#039;s Spine",fr:"Colonne du Dragon",de:"Stachel des Drachen",ru:"Драконий Хребет"}},
{x:18837,y:-25162,type:5, level:0, icon:"", name:{en:"Lucenthead Hurst",fr:"Horst Etincelant",de:"Grat des Funkelnden Waldes",ru:"Сопка Сверкающая Голова"}},
{x:19276,y:-26002,type:5, level:0, icon:"", name:{en:"Dragon&#039;s Gullet Impasse",fr:"Impasse de la Gorge du Dragon",de:"Drachenschlund-Klamm",ru:"Глотка Дракона "}},
{x:18101,y:-25620,type:5, level:0, icon:"", name:{en:"Flaming Forest",fr:"Forêt Enflammée",de:"Flammender Wald",ru:"Пылающий лес"}},
{x:17860,y:-26047,type:5, level:0, icon:"", name:{en:"Varynx Haunt",fr:"Repère des Varinx",de:"Varinx-Revier",ru:"Обиталище Варинксов"}},
{x:17506,y:-26304,type:5, level:0, icon:"", name:{en:"Secret Kami Oasis",fr:"Oasis Secret des Kamis",de:"Geheime Kami-Oase",ru:"Тайный Оазис Ками"}},
{x:25837,y:-24278,type:5, level:0, icon:"", name:{en:"Karavan Camp of Aelius Dunes",fr:"Camp Karavan des Dunes d&#039;Aelius",de:"Karavan-Lager der Aelius-Dünen",ru:"Лагерь Каравана в дюнах Аэлиуса"}},
{x:24902,y:-24011,type:5, level:0, icon:"", name:{en:"Kami Camp of Aelius Dunes",fr:"Camp Kami des Dunes d&#039;Aelius",de:"Kami-Lager der Aelius-Dünen",ru:"Лагерь Ками в дюнах Аэлиуса"}},
{x:2735,y:-17124,type:5, level:0, icon:"", name:{en:"Cattle Room",fr:"Salle d&#039;élevage",de:"Zuchtkammer",ru:"cattle room"}},
{x:2016,y:-16704,type:5, level:0, icon:"", name:{en:"Dark Mines",fr:"Mines Obscures",de:"Dunkle Minen",ru:"NotFound:(place)ru.kitiniere_dark_mines.place"}},
{x:2027,y:-16979,type:5, level:0, icon:"", name:{en:"Prime Eggs Room",fr:"Chambre des oeufs primaires",de:"Haupt-Gelegeraum",ru:"NotFound:(place)ru.kitiniere_eggs_room.place"}},
{x:2699,y:-16881,type:5, level:0, icon:"", name:{en:"Old Mines",fr:"Mines Anciennes",de:"Alte Minen",ru:"NotFound:(place)ru.kitiniere_old_mines.place"}},
{x:2399,y:-16500,type:5, level:0, icon:"", name:{en:"Princes&#039; Room",fr:"Salle des princes",de:"Raum der Prinzen",ru:"NotFound:(place)ru.kitiniere_princes_room.place"}},
{x:2372,y:-16956,type:5, level:0, icon:"", name:{en:"Queen&#039;s Room",fr:"Salle de la reine",de:"Halle der Königin",ru:"NotFound:(place)ru.kitiniere_queen_room.place"}},
{x:4653,y:-836,type:5, level:0, icon:"", name:{en:"Mullgrove",fr:"Bosquet Inférieur",de:"Kapwald",ru:"Маллгроув"}},
{x:4499,y:-904,type:5, level:0, icon:"", name:{en:"Eastgrove Gate",fr:"Porte du Bosquet Est",de:"Ostwaldpforte",ru:"Врата Восточной рощи"}},
{x:4119,y:-1086,type:5, level:0, icon:"", name:{en:"Westgrove Gate",fr:"Porte du Bosquet Ouest",de:"Westwaldpforte",ru:"Врата Западной рощи"}},
{x:4974,y:-625,type:5, level:0, icon:"", name:{en:"Highgrove",fr:"Bosquet Supérieur",de:"Hochwald",ru:"Вышняя роща"}},
{x:1868,y:-1664,type:5, level:0, icon:"", name:{en:"Little Mountain",fr:"Petite Montagne",de:"kleiner Berg",ru:"Маленькая гора"}},
{x:1272,y:-806,type:5, level:0, icon:"", name:{en:"Virginia Falls",fr:"Chutes de Virginia",de:"Virginia-Wasserfall",ru:"Водопад Виргиния"}},
{x:710,y:-821,type:5, level:0, icon:"", name:{en:"Tylini Gate",fr:"Porte de Tylini",de:"Tylini-Pforte",ru:"Врата Тайлини"}},
{x:5524,y:-7762,type:5, level:0, icon:"", name:{en:"Maze of Sprite",fr:"Labyrinthe des Lutins",de:"Geisterlabyrinth",ru:"Лабиринт Фей"}},
{x:5903,y:-7516,type:5, level:0, icon:"", name:{en:"Chilling Swamp",fr:"Marais des Frissons",de:"Sumpf der Angst",ru:"Знобкое Болото "}},
{x:5828,y:-6802,type:5, level:0, icon:"", name:{en:"Falls of the Two Totems",fr:"Chutes des Deux Totems",de:"Wasserfall der zwei Totems",ru:"Водопады двух Тотемов"}},
{x:5518,y:-6831,type:5, level:0, icon:"", name:{en:"Folly plain",fr:"Plaine de la Folie",de:"Ebene der Torheit",ru:"Равнина недомыслия"}},
{x:3915,y:-5672,type:5, level:0, icon:"", name:{en:"Fencoomb Ponds ",fr:"Etangs de Fencoomb",de:"Moorteiche",ru:"Пруды Фенкумба"}},
{x:4165,y:-5926,type:5, level:0, icon:"", name:{en:"Fearing Fens",fr:"Marécages de l&#039;Angoisse",de:"gefürchteter Sumpf",ru:"Трясина испуга"}},
{x:4245,y:-6159,type:5, level:0, icon:"", name:{en:"Slough of the Demon",fr:"Abîme du Démon",de:"Dämonenmoor",ru:"Топи Демона"}},
{x:4154,y:-6673,type:5, level:0, icon:"", name:{en:"Panting Pass",fr:"Col des Palpitations",de:"schwieriger Pfad",ru:"Удушливый перевал"}},
{x:2401,y:-2084,type:5, level:0, icon:"", name:{en:"Tunnel of Woe",fr:"Tunnel des Malheurs",de:"Unglückstunnel",ru:"Тоннель страданий"}},
{x:2875,y:-2079,type:5, level:0, icon:"", name:{en:"Runninghill Pass",fr:"Col Vallonné",de:"Gebirgspass",ru:"Ущелье Бегущего холма"}},
{x:3281,y:-2479,type:5, level:0, icon:"", name:{en:"Towerbridge Way",fr:"Route de Towerbridge",de:"Turmbrückenweg",ru:"Дороги у Башенного Моста"}},
{x:3198,y:-1756,type:5, level:0, icon:"", name:{en:"Torbak Trail Hill",fr:"Sentier des Torbaks",de:"Anhöhe der Torbaks",ru:"Холм Тропы Торбаков"}},
{x:3606,y:-1849,type:5, level:0, icon:"", name:{en:"Killing Tree",fr:"Arbre au Massacre",de:"Todesbaum",ru:"Дерево - убийца"}},
{x:3844,y:-1758,type:5, level:0, icon:"", name:{en:"Smitten Mount",fr:"Montagne du Tourment",de:"Berg der Pein",ru:"Обрушенная гора"}},
{x:3679,y:-2869,type:5, level:0, icon:"", name:{en:"Psykopla Knoll",fr:"Monticule des Psykoplas",de:"Psykopla-Hügel",ru:"Холмы Псикопл "}},
{x:4158,y:-3520,type:5, level:0, icon:"", name:{en:"Matis Arena",fr:"Arène Matis",de:"Matis-Arena",ru:"Арена матисов"}},
{x:4835,y:-4781,type:5, level:0, icon:"", name:{en:"Charmers&#039; Way",fr:"Route des Charmeurs",de:"Weg der Charmeure",ru:"Дорога Чародеев"}},
{x:5935,y:-5906,type:5, level:0, icon:"", name:{en:"Kami Circle",fr:"Cercle Kamic",de:"Kami-Kreis",ru:"Круг Ками"}},
{x:5356,y:-5925,type:5, level:0, icon:"", name:{en:"The Trove",fr:"Trésor",de:"Der Hort",ru:"Сокровищница"}},
{x:4488,y:-5523,type:5, level:0, icon:"", name:{en:"Den of Fury",fr:"Antre de la Fureur",de:"Höhle des Zorns",ru:"Логово ярости"}},
{x:3964,y:-4999,type:5, level:0, icon:"", name:{en:"The Rising",fr:"Poussée",de:"Erhebung",ru:"Возвышение"}},
{x:15109,y:-1274,type:5, level:0, icon:"", name:{en:"Kami Camp of Almati Wood",fr:"Camp Kami du Bois d&#039;Almati",de:"Kami-Lager des Almati-Waldes",ru:"Лагерь Ками в лесу Алмати"}},
{x:14347,y:-641,type:5, level:0, icon:"", name:{en:"Karavan Camp of Almati Wood",fr:"Camp Karavan du Bois d&#039;Almati",de:"Karavan-Lager des Almati-Waldes",ru:"Лагерь Каравана в дюнах Аэлиуса"}},
{x:10572,y:-11115,type:5, level:0, icon:"", name:{en:"Hunting grounds",fr:"Terrains de chasse",de:"Jagdgründe",ru:"Охотничьи Угодья"}},
{x:9795,y:-10994,type:5, level:0, icon:"", name:{en:"Shattered ruins",fr:"Ruines dévastées",de:"Zerstörte Ruinen",ru:"Разрушенный город"}},
{x:9860,y:-10966,type:5, level:0, icon:"", name:{en:"Ruins of Silan",fr:"Ruines de Silan",de:"Ruinen von Silan",ru:"Руины Силана"}},
{x:9672,y:-10784,type:5, level:0, icon:"", name:{en:"Throne room",fr:"Salle du trône",de:"Thronsaal",ru:"Тронный зал"}},
{x:10265,y:-11671,type:5, level:0, icon:"", name:{en:"Rangers&#039; land",fr:"contrée des Rangers",de:"Gebiet der Ranger",ru:"Земля Рэйнджеров"}},
{x:10160,y:-11599,type:5, level:0, icon:"", name:{en:"Arena",fr:"Arène",de:"Arena",ru:"Арена"}},
{x:9529,y:-11411,type:5, level:0, icon:"", name:{en:"Blight zone",fr:"Pays malade",de:"Krankes Land",ru:"Зона поражения"}},
{x:9043,y:-10851,type:5, level:0, icon:"", name:{en:"Shining Lake",fr:"Lac étincelant",de:"Funkelnder See",ru:"Сверкающее озеро"}},
{x:8398,y:-10636,type:5, level:0, icon:"", name:{en:"Kitins Jungle",fr:"Jungle aux Kitins",de:"Kitin-Dschungel",ru:"Джунгли Китинов"}},
{x:10407,y:-11864,type:5, level:0, icon:"", name:{en:"Karavan Embassy",fr:"Ambassade Karavan",de:"Karavan-Botschaft",ru:"Посольство Каравана"}},
{x:10423,y:-11683,type:5, level:0, icon:"", name:{en:"Kami Enclave",fr:"Enclave Kami",de:"Kami-Enklave",ru:"Анклав Ками"}},
{x:9518,y:-6627,type:5, level:0, icon:"", name:{en:"The Concha",fr:"Conque",de:"Die Muschel",ru:"Конха"}},
{x:9127,y:-6869,type:5, level:0, icon:"", name:{en:"Destiny&#039;s End",fr:"Fin de la Destinée",de:"Schicksalsende",ru:"Роковой Предел"}},
{x:8560,y:-7088,type:5, level:0, icon:"", name:{en:"Hammer Hills",fr:"Colline Martelée",de:"Hammerhöhen",ru:"Холмы - Молоты"}},
{x:9054,y:-7667,type:5, level:0, icon:"", name:{en:"The Forsaken Camp",fr:"Campement Abandonné",de:"Das verlassene Lager",ru:"Покинутый лагерь"}},
{x:5782,y:-10248,type:5, level:0, icon:"", name:{en:"Ruins of Leron",fr:"Ruines de Léron",de:"Ruinen von Leron",ru:"Руины Лероны"}},
{x:5648,y:-10617,type:5, level:0, icon:"", name:{en:"Halls of Darkring",fr:"Salles de la Bague Noire",de:"Hallen des Schwarzen Rings",ru:"Залы Темного Кольца"}},
{x:6080,y:-11341,type:5, level:0, icon:"", name:{en:"The Fallen Tree",fr:"Arbre Abattu",de:"Der gefallene Baum",ru:"Падшее Дерево"}},
{x:6058,y:-11905,type:5, level:0, icon:"", name:{en:"Windygate Column",fr:"Colonne de la Porte des Vents",de:"Säule der Sturmpforte",ru:"Колонна Ветряных Врат"}},
{x:5869,y:-12418,type:5, level:0, icon:"", name:{en:"Land of Plenty",fr:"Terre d&#039;Abondance",de:"Land des Überflusses",ru:"Земли Изобилия"}},
{x:6280,y:-12217,type:5, level:0, icon:"", name:{en:"Highwell",fr:"Flaque Supérieur",de:"Oberer Schacht",ru:"Верхние Колодцы"}},
{x:7069,y:-12639,type:5, level:0, icon:"", name:{en:"Underwood Woe",fr:"Sous-Bois du Malheur",de:"Unterholz des Unglücks",ru:"Горе Подлесное"}},
{x:6639,y:-12958,type:5, level:0, icon:"", name:{en:"Grotto Pass",fr:"Col des Grottes",de:"Höhlenpass",ru:"Проход Грота"}},
{x:6091,y:-13251,type:5, level:0, icon:"", name:{en:"Three Totems Pass",fr:"Col des Trois Totems",de:"Dreitotempass",ru:"Проход Трех Тотемов"}},
{x:6524,y:-13305,type:5, level:0, icon:"", name:{en:"Giant Mushroom Pass",fr:"Col du Champignon Géant",de:"Riesenpilzpass",ru:"Проход Грибов Гигантов"}},
{x:6071,y:-13755,type:5, level:0, icon:"", name:{en:"Alleyways Bluff",fr:"Ruelle",de:"Klippendurchgang",ru:"Утес трех переулков"}},
{x:6085,y:-14271,type:5, level:0, icon:"", name:{en:"High Henge",fr:"Cromlech Supérieur",de:"Oberer Steinkreis",ru:"Высокие Мезолиты"}},
{x:6480,y:-14963,type:5, level:0, icon:"", name:{en:"Lowhills",fr:"Basses Collines",de:"Kleine Hügel",ru:"Малохолмье"}},
{x:6635,y:-15688,type:5, level:0, icon:"", name:{en:"Darkenwell",fr:"Flaque Sombre",de:"Dunkler Schacht",ru:"Черный омут"}},
{x:6263,y:-15999,type:5, level:0, icon:"", name:{en:"Eerie Valley",fr:"Vallée Sinistre",de:"Schauriges Tal",ru:"Долина Ужаса"}},
{x:5754,y:-16483,type:5, level:0, icon:"", name:{en:"Yelkgrove",fr:"Bosquet des Yelks",de:"Yelkwäldchen",ru:"Роща Йелков"}},
{x:7024,y:-16845,type:5, level:0, icon:"", name:{en:"Spooky End",fr:"Limite de l&#039;Angoisse",de:"Seltsames Ende",ru:"Мрачный Предел"}},
{x:3278,y:-10319,type:5, level:0, icon:"", name:{en:"Deadtree Hole",fr:"Trou aux Arbres Morts",de:"Grube des toten Baumes",ru:"Яма Мертводрева"}},
{x:3600,y:-10475,type:5, level:0, icon:"", name:{en:"Sap Marsh",fr:"Marécage de la Sève",de:"Sapsumpf",ru:"Болота сэп"}},
{x:3128,y:-10639,type:5, level:0, icon:"", name:{en:"Furtive Waters",fr:"Eaux Furtives",de:"Tückische Wasser",ru:"Потаенные Воды"}},
{x:3281,y:-10641,type:5, level:0, icon:"", name:{en:"Ruins of Tryde",fr:"Ruines de Tryde",de:"Ruinen von Tryde",ru:"Руины Трайда"}},
{x:2798,y:-10576,type:5, level:0, icon:"", name:{en:"Shooting Meadow",fr:"Pré Lancinant",de:"Stechende Wiese",ru:"Луг Застрельщиков"}},
{x:699,y:-14462,type:5, level:0, icon:"", name:{en:"Wings of Spite",fr:"Ailes du Dépit",de:"Flügel der Feindschaft",ru:"Крылья Досады"}},
{x:485,y:-13887,type:5, level:0, icon:"", name:{en:"Great Mushroom Wood",fr:"Bois du Champignon Géant",de:"Großer Pilzwald",ru:"Великие Грибные Леса "}},
{x:987,y:-13590,type:5, level:0, icon:"", name:{en:"The Cursed Cavern",fr:"Caverne Maudite",de:"Die verfluchte Höhle",ru:"Проклятая Пещера"}},
{x:959,y:-13279,type:5, level:0, icon:"", name:{en:"Grotto Walk",fr:"Promenade des Grottes",de:"Grottenweg",ru:"Тропа Грота"}},
{x:1599,y:-14402,type:5, level:0, icon:"", name:{en:"Midway Point",fr:"Point du Milieu",de:"Mittelpunkt",ru:"Срединное Место"}},
{x:1983,y:-13585,type:5, level:0, icon:"", name:{en:"Saplake Major",fr:"Lac Majeur de Sève",de:"Großer Sapsee",ru:"Большое озеро сэп"}},
{x:2715,y:-13974,type:5, level:0, icon:"", name:{en:"Haunted Gorge",fr:"Gorge Hantée",de:"Schlucht des Spuks",ru:"Ущелье Призраков"}},
{x:2251,y:-14553,type:5, level:0, icon:"", name:{en:"Dragon Horns Valley",fr:"Vallée des Cornes du Dragon",de:"Drachenhorntal",ru:"Долина Драконова Рога"}},
{x:1925,y:-14722,type:5, level:0, icon:"", name:{en:"Cursed Impasse",fr:"Impasse Maudite",de:"Verfluchte Sackgasse",ru:"Проклятый Тупик"}},
{x:2576,y:-15193,type:5, level:0, icon:"", name:{en:"Hall of the Mountain Bane",fr:"Caverne de la Montagne Empoisonnée",de:"Halle des vergifteten Berges",ru:"Зал Горного Бедствия "}},
{x:2245,y:-15512,type:5, level:0, icon:"", name:{en:"Demon&#039;s Lap",fr:"Giron du Démon",de:"Dämonenschoß",ru:"Ложбина Демона"}},
{x:19285,y:-31925,type:5, level:0, icon:"", name:{en:"Gusty Gorge",fr:"Gorge des Vents",de:"Stürmische Schlucht",ru:"Теснина Ветров"}},
{x:18558,y:-29913,type:5, level:0, icon:"", name:{en:"Lake Superior",fr:"Lac Supérieur",de:"Großer See",ru:"Озеро Верхнее"}},
{x:17472,y:-30310,type:5, level:0, icon:"", name:{en:"Hush Hole",fr:"Trou du Silence",de:"Grube der Stille",ru:"Нора Тссс!"}},
{x:14755,y:-30463,type:5, level:0, icon:"", name:{en:"Witchy Coves",fr:"Criques Ensorcelées",de:"Verzauberte Bucht",ru:"Пещеры Ведьм "}},
{x:15434,y:-30345,type:5, level:0, icon:"", name:{en:"Muse Watch Lake",fr:"Lac des Veilleurs de Songe",de:"See der Traumwächter",ru:"Озеро Наблюдающих за Музами"}},
{x:16256,y:-30153,type:5, level:0, icon:"", name:{en:"Big Sleep Mountain",fr:"Montagne du Profond Sommeil",de:"Schlafender Berg",ru:"Гора Великого Сна"}},
{x:16054,y:-30577,type:5, level:0, icon:"", name:{en:"Windy Way",fr:"Route des Vents",de:"Weg der Winde",ru:"Дороги Ветров"}},
{x:13950,y:-31682,type:5, level:0, icon:"", name:{en:"Torbak Spread",fr:"Vallée des Torbaks",de:"Tal der Torbaks",ru:"Торбацкие Просторы"}},
{x:14248,y:-31845,type:5, level:0, icon:"", name:{en:"Cute Springs",fr:"Sources des Cutes",de:"Cute-Quellsee",ru:"Ключи Кьют"}},
{x:14312,y:-32089,type:5, level:0, icon:"", name:{en:"Cute Springs Twining",fr:"Sources Agitées des Cutes",de:"Sprudelnde Cute-Quellen",ru:"Плетение Кьют"}},
{x:14954,y:-31931,type:5, level:0, icon:"", name:{en:"Liberty Gateway",fr:"Porte de la Liberté",de:"Tor zur Freiheit",ru:"Врата Вольности"}},
{x:14819,y:-32737,type:5, level:0, icon:"", name:{en:"Twin Tops",fr:"Cimes Jumelles",de:"Zwillingsgipfel",ru:"Пики Близнецы"}},
{x:15037,y:-33108,type:5, level:0, icon:"", name:{en:"Rift of Strife",fr:"Crevasse de la Dissension",de:"Spalte des Unfriedens",ru:"Разлом Противостояния"}},
{x:15367,y:-33770,type:5, level:0, icon:"", name:{en:"Deathfly Plain",fr:"Plaine Perdue",de:"Verlassene Ebene",ru:"Роковая Равнина"}},
{x:15266,y:-33999,type:5, level:0, icon:"", name:{en:"Fount Porch",fr:"Porche des Sources",de:"Quellhalle",ru:"Террасы Родника"}},
{x:15023,y:-33968,type:5, level:0, icon:"", name:{en:"Fount Lake",fr:"Lac des Sources",de:"Quellsee",ru:"Озеро Родника"}},
{x:15600,y:-34633,type:5, level:0, icon:"", name:{en:"Southlakes",fr:"Lacs du Sud",de:"Seen des Südens",ru:"Южные Озера"}},
{x:15925,y:-34627,type:5, level:0, icon:"", name:{en:"Ponders End Pillars",fr:"Colonnes de la Méditation",de:"Säulen der Besinnung",ru:"Колонны Предела Раздумий"}},
{x:18056,y:-33597,type:5, level:0, icon:"", name:{en:"Tippy Peaks",fr:"Pics Instables",de:"Brüchige Gipfel",ru:"Острые Пики"}},
{x:17924,y:-33925,type:5, level:0, icon:"", name:{en:"Baily Lagoon",fr:"Lagon à la Dérive",de:"Lagune des Driftens",ru:"Лагуна Бэйли"}},
{x:17358,y:-34558,type:5, level:0, icon:"", name:{en:"Mire of the Dire",fr:"Bourbier de la Misère",de:"Grässlicher Morast",ru:"Зловещая Трясина"}},
{x:17724,y:-34643,type:5, level:0, icon:"", name:{en:"Graveyard Walk",fr:"Promenade Caverneuse",de:"Friedhofsweg",ru:"Кладбищенская тропа"}},
{x:18299,y:-34019,type:5, level:0, icon:"", name:{en:"Enchanted Circle",fr:"Cercle Enchanté",de:"Verzauberter Kreis",ru:"Зачарованный круг"}},
{x:16140,y:-31892,type:5, level:0, icon:"", name:{en:"Darkmoor",fr:"Landes Obscures",de:"Schwarzmoor",ru:"Мрачные Топи"}},
{x:17607,y:-32201,type:5, level:0, icon:"", name:{en:"Lakenisle",fr:"Lac de l&#039;Ile",de:"Seeninsel",ru:"Озерная отмель"}},
{x:18383,y:-32883,type:5, level:0, icon:"", name:{en:"Blackwater",fr:"Eaux Obscures",de:"Dunkles Wasser",ru:"Черноводье"}},
{x:25664,y:-30468,type:5, level:0, icon:"", name:{en:"Karavan Camp of Olkern Lake",fr:"Camp Karavan du Lac d&#039;Olkern",de:"Karavan-Lager des Olkern-Sees",ru:"Лагерь Каравана у озера Олкерн"}},
{x:24912,y:-29705,type:5, level:0, icon:"", name:{en:"Kami Camp of Olkern Lake",fr:"Camp Kami du Lac d&#039;Olkern",de:"Kami-Lager des Olkern-Sees",ru:"Лагерь Ками у озера Олкерн"}},
{x:9849,y:-4552,type:5, level:0, icon:"", name:{en:"Kipee Mull",fr:"Promontoire des Kipees",de:"Kap der Kipees",ru:"Мыс Киппи"}},
{x:10318,y:-4244,type:5, level:0, icon:"", name:{en:"Sly Lake",fr:"Lac Dissimulé",de:"Verborgener See",ru:"Озеро Коварства"}},
{x:10866,y:-4563,type:5, level:0, icon:"", name:{en:"Underway Arch",fr:"Arc Caché",de:"Wölbung",ru:"Свод Подземелий"}},
{x:11666,y:-5120,type:5, level:0, icon:"", name:{en:"Withered Stock",fr:"Souche Flétrie",de:"Verdorrter Stamm",ru:"Заброшенный Кладезь "}},
{x:8883,y:-3285,type:5, level:0, icon:"", name:{en:"Still Waters",fr:"Eaux Paisibles",de:"Stille Wasser",ru:"Недвижные воды"}},
{x:9203,y:-3865,type:5, level:0, icon:"", name:{en:"Mossy Scarp",fr:"Escarpement Moussu",de:"moosige Böschung",ru:"Замшелый откос"}},
{x:9841,y:-3760,type:5, level:0, icon:"", name:{en:"Mektoub Waterhole",fr:"Mare des Mektoubs",de:"Mektoub-Wasserloch",ru:"Водопой Мектубов"}},
{x:9524,y:-4232,type:5, level:0, icon:"", name:{en:"Mystic Falls",fr:"Chutes Mystiques",de:"mystischer Wasserfall",ru:"Водопады Тайн"}},
{x:10453,y:-3380,type:5, level:0, icon:"", name:{en:"Palm Valley",fr:"Vallée des Palmiers",de:"Tal der Palmen",ru:"Долина Пальм"}},
{x:10760,y:-3761,type:5, level:0, icon:"", name:{en:"Maiden Pond",fr:"Etang Vierge",de:"Jungfernteich",ru:"Девственный Пруд"}},
{x:10496,y:-4061,type:5, level:0, icon:"", name:{en:"Slavenhurst",fr:"Boissclave",de:"Sklavenwald",ru:"Холм Славини"}},
{x:11611,y:-3449,type:5, level:0, icon:"", name:{en:"Fowling Lake",fr:"Lac aux Oiseaux",de:"Vogelsee",ru:"Озеро Птицеловов"}},
{x:11692,y:-3117,type:5, level:0, icon:"", name:{en:"Great Boulder Tunnel",fr:"Grand Tunnel Rocailleux",de:"Großer Brocken-Tunnel",ru:"Тоннель Великой глыбы"}},
{x:11506,y:-1917,type:5, level:0, icon:"", name:{en:"Paramount Stock",fr:"Souche Capitale",de:"Stamm der Aussicht",ru:"Верховный Кладезь"}},
{x:10107,y:-2132,type:5, level:0, icon:"", name:{en:"The Lost Valley",fr:"Vallée Perdue",de:"Das verlorene Tal",ru:"Затерянная долина"}},
{x:11808,y:-2513,type:5, level:0, icon:"", name:{en:"Mull of Despond",fr:"Promontoire du Désespoir",de:"Kap der Verzweiflung",ru:"Чащобы безнадежности"}},
{x:9511,y:-2293,type:5, level:0, icon:"", name:{en:"Bighorn Mountain",fr:"Montagne aux Cornes",de:"Hornberg",ru:"Гора Бигхорн"}},
{x:9355,y:-2479,type:5, level:0, icon:"", name:{en:"Fustylake",fr:"Lac Poussiéreux",de:"Stinkender See",ru:"Прогорклое озеро"}},
{x:9483,y:-2964,type:5, level:0, icon:"", name:{en:"Kincher Arch",fr:"Arc des Kinchers",de:"Kincherbogen",ru:"Арка Кинчеров"}},
{x:7190,y:-1996,type:5, level:0, icon:"", name:{en:"The Great Outback",fr:"Arrière Pays",de:"Großes Buschland",ru:"Великая Целина"}},
{x:7513,y:-2236,type:5, level:0, icon:"", name:{en:"Desertstock",fr:"Désertstock",de:"Trockener Stamm",ru:"Пустынный кладезь"}},
{x:7868,y:-2411,type:5, level:0, icon:"", name:{en:"Stainmoor",fr:"Lande Tachetée",de:"Fleckenmoor",ru:"Торфяники Стэйнмура"}},
{x:8081,y:-2325,type:5, level:0, icon:"", name:{en:"Stainmoor Gate",fr:"Porte de la Lande Tachetée",de:"Fleckenmoorpforte",ru:"Врата Стэйнмура"}},
{x:8245,y:-1835,type:5, level:0, icon:"", name:{en:"Highland Impasse",fr:"Impasse des Hautes Terres",de:"Hochland-Pass",ru:"Непроходимое Нагорье"}},
{x:8074,y:-3286,type:5, level:0, icon:"", name:{en:"Hopedell",fr:"Vallon des Espérances",de:"Tal der Hoffnung",ru:"Хоупделл"}},
{x:1039,y:-10535,type:4, level:200, icon:"", name:{en:"Abyss of Ichor",fr:"Gouffre d&#039;Ichor",de:"Abgrund von Ichor",ru:"Кровоточащая бездна"}},
{x:18853,y:-24670,type:4, level:50, icon:"", name:{en:"Imperial Dunes",fr:"Dune Impériale",de:"Imperiale Dünen",ru:"Имперские дюны"}},
{x:17788,y:-25026,type:4, level:100, icon:"", name:{en:"Oflovak&#039;s Oasis",fr:"Oasis d&#039;Oflovak",de:"Oflovaks Oase",ru:"Оазис Офловака"}},
{x:17118,y:-25188,type:4, level:150, icon:"", name:{en:"Frahar Towers",fr:"Tours de Frahar",de:"Frahar-Türme",ru:"Башни фрахаров"}},
{x:19692,y:-25354,type:4, level:150, icon:"", name:{en:"Sawdust Mines",fr:"Mines de Sciure",de:"Sägemehlminen",ru:"Древесная шахта"}},
{x:16399,y:-24959,type:4, level:200, icon:"", name:{en:"Dunes of Exile",fr:"Dunes de l&#039;Exil",de:"Dünen der Verbannung",ru:"Дюны Изгнания"}},
{x:19118,y:-26510,type:4, level:200, icon:"", name:{en:"Savage Dunes",fr:"Dunes Sauvages",de:"Wilde Dünen",ru:"Дикие дюны"}},
{x:19419,y:-24957,type:4, level:200, icon:"", name:{en:"Outlaw Canyon",fr:"Canyon Interdit",de:"Canyon der Gesetzlosen",ru:"Каньон Беззакония"}},
{x:17387,y:-26107,type:4, level:250, icon:"", name:{en:"Scorched Corridor",fr:"Couloir Brûlé",de:"Sengende Schlucht",ru:"Выжженный коридор"}},
{x:25358,y:-24164,type:4, level:0, icon:"", name:{en:"Aelius Dunes",fr:"Dunes d&#039;Aelius",de:"Aelius-Dünen",ru:"Дюны Аэлиуса"}},
{x:22085,y:-26165,type:4, level:0, icon:"", name:{en:"Fyros Island",fr:"Ile Fyros",de:"Fyros-Insel",ru:"Континент файросов"}},
{x:2356,y:-16864,type:4, level:0, icon:"", name:{en:"Kitins&#039; Lair",fr:"Kitinière",de:"Kitin-Nest",ru:"Логово китинов"}},
{x:4520,y:-1106,type:4, level:250, icon:"", name:{en:"Grove of Confusion",fr:"Bosquet de la Confusion",de:"Hain der Verwirrung",ru:"Смятенная роща"}},
{x:1411,y:-1184,type:4, level:200, icon:"", name:{en:"Hidden Source",fr:"Source Cachée",de:"Versteckte Quelle",ru:"Потаенный источник"}},
{x:5484,y:-7053,type:4, level:200, icon:"", name:{en:"Heretic&#039;s Hovel",fr:"Masure de l&#039;Hérétique",de:"Ketzers Hütte",ru:"Логово еретиков"}},
{x:3961,y:-5968,type:4, level:200, icon:"", name:{en:"Upper Bog",fr:"Marais Supérieur",de:"Oberer Sumpf",ru:"Верховые топи"}},
{x:2834,y:-2092,type:4, level:150, icon:"", name:{en:"Knoll of Dissent",fr:"Tertre de la Dissidence",de:"Hügel der Abtrünnigen",ru:"Холмы раскола"}},
{x:4142,y:-3703,type:4, level:50, icon:"", name:{en:"Majestic Garden",fr:"Jardin Majestueux",de:"Majestätischer Garten",ru:"Сады Величия"}},
{x:4996,y:-5649,type:4, level:100, icon:"", name:{en:"Fleeting Garden",fr:"Jardin Fugace",de:"Vergänglicher Garten",ru:"Ускользающий сад"}},
{x:14710,y:-968,type:4, level:0, icon:"", name:{en:"Almati Wood",fr:"Bois d&#039;Almati",de:"Almati-Wald",ru:"Леса Алмати"}},
{x:1462,y:-6632,type:4, level:0, icon:"", name:{en:"Matis Island",fr:"Ile Matis",de:"Matis-Insel",ru:"Континент матисов"}},
{x:9696,y:-11195,type:4, level:0, icon:"", name:{en:"Lands to Explore",fr:"Contrées à explorer",de:"Die Entdeckenswerten Gefilde",ru:"Малоизученные Земли "}},
{x:8786,y:-7196,type:4, level:200, icon:"", name:{en:"Nexus",fr:"Nexus",de:"Nexus",ru:"Нексус"}},
{x:5921,y:-10726,type:4, level:150, icon:"", name:{en:"Windy Gate",fr:"Porte des Vents",de:"Pforte des Sturms",ru:"Врата Ветров"}},
{x:6479,y:-12802,type:4, level:200, icon:"", name:{en:"Elusive Forest",fr:"Forêt Insaisissable",de:"Unergründlicher Wald",ru:"Эфемерный лес"}},
{x:6399,y:-14720,type:4, level:150, icon:"", name:{en:"Gate of Obscurity",fr:"Porte de l&#039;Obscurité",de:"Tor der Dunkelheit",ru:"Врата неопределенности"}},
{x:6240,y:-16324,type:4, level:200, icon:"", name:{en:"Trench of Trials",fr:"La Fosse aux Epreuves",de:"Graben der Heimsuchung",ru:"Ров Испытаний"}},
{x:3200,y:-10522,type:4, level:250, icon:"", name:{en:"Under Spring",fr:"Sources Interdites",de:"Verbotene Quellen",ru:"Подземный источник"}},
{x:1009,y:-14080,type:4, level:250, icon:"", name:{en:"Land of Continuity",fr:"Terre de la Continuité",de:"Land der Kontinuität",ru:"Земли непрерывности"}},
{x:2229,y:-13846,type:4, level:250, icon:"", name:{en:"Sunken City",fr:"Cité Engloutie",de:"Versunkene Stadt",ru:"Погребенный город"}},
{x:2147,y:-15178,type:4, level:250, icon:"", name:{en:"Forbidden Depths",fr:"Profondeurs Interdites",de:"Verbotene Tiefen",ru:"Запретные Глубины"}},
{x:18557,y:-30800,type:4, level:250, icon:"", name:{en:"Lagoons of Loria",fr:"Lagons de Loria",de:"Lagunen von Loria",ru:"Лагуны Лории"}},
{x:15675,y:-30635,type:4, level:100, icon:"", name:{en:"Winds of Muse",fr:"Vents du Songe",de:"Winde der Musen",ru:"Ветра Муз"}},
{x:14480,y:-32391,type:4, level:200, icon:"", name:{en:"Bounty Beaches",fr:"Plages d&#039;Abondance",de:"Strände des Überflusses",ru:"Отмели Изобилия"}},
{x:15279,y:-34153,type:4, level:150, icon:"", name:{en:"Fount",fr:"Source",de:"Ursprung",ru:"Родник"}},
{x:17763,y:-34160,type:4, level:200, icon:"", name:{en:"Enchanted Isle",fr:"Ile Enchantée",de:"Verzauberte Insel",ru:"Зачарованный Остров"}},
{x:16971,y:-32222,type:4, level:50, icon:"", name:{en:"Liberty Lake",fr:"Lac de la Liberté",de:"See der Freiheit",ru:"Озеро Свободы"}},
{x:17055,y:-31481,type:4, level:100, icon:"", name:{en:"Dew Drops",fr:"Chutes de la Rosée",de:"Tautropfen",ru:"Капли Росы"}},
{x:16396,y:-33785,type:4, level:150, icon:"", name:{en:"Resting Water",fr:"Eau du Repos",de:"Ruhiges Wasser",ru:"Воды Спокойствия"}},
{x:25276,y:-30076,type:4, level:0, icon:"", name:{en:"Olkern Lake",fr:"Lac D&#039;Olkern",de:"Olkern-See",ru:"Озеро Олкерн"}},
{x:22004,y:-33918,type:4, level:0, icon:"", name:{en:"Tryker Island",fr:"Ile Tryker",de:"Tryker-Insel",ru:"Континент трайкеров"}},
{x:10957,y:-4721,type:4, level:200, icon:"", name:{en:"Grove of Umbra",fr:"Bosquet de l&#039;Ombre",de:"Hain von Umbra",ru:"Сумеречная роща"}},
{x:9460,y:-3499,type:4, level:50, icon:"", name:{en:"Cities of Intuition",fr:"Cités de l&#039;Intuition",de:"Städte der Einsicht",ru:"Города Провидцев"}},
{x:11017,y:-3359,type:4, level:100, icon:"", name:{en:"Maiden Grove",fr:"Bosquet Vierge",de:"Jungfräuliches Wäldchen",ru:"Роща Дев"}},
{x:10959,y:-2344,type:4, level:250, icon:"", name:{en:"Void",fr:"Vide",de:"Das Nichts",ru:"Великая Пустота"}},
{x:9493,y:-2640,type:4, level:150, icon:"", name:{en:"Haven of Purity",fr:"Havre de Pureté",de:"Hafen der Reinheit",ru:"Прибежище Благочестия"}},
{x:7917,y:-2559,type:4, level:200, icon:"", name:{en:"Knot of Dementia",fr:"Noeud de la Démence",de:"Knoten der Demenz",ru:"Узел безумия"}},
{x:8063,y:-4910,type:4, level:0, icon:"", name:{en:"Zoraï Island",fr:"Ile Zoraï",de:"Zorai-Insel",ru:"Остров Зораи"}},
{x:18579,y:-24305,type:3, level:0, icon:"lm_continent.png", name:{en:"North Pyr Stables",fr:"Etables Nord de Pyr",de:"Pyr Nord-Ställe",ru:"Стойла Северного Пайра"}},
{x:18789,y:-24620,type:3, level:0, icon:"lm_continent.png", name:{en:"South Pyr Stables",fr:"Etables Sud de Pyr",de:"Pyr Süd-Ställe",ru:"Стойла Южного Пайра"}},
{x:18968,y:-24415,type:3, level:0, icon:"lm_continent.png", name:{en:"East Pyr Stables",fr:"Etables Est de Pyr",de:"Pyr Ost-Ställe",ru:"Стойла Восточного Пайра"}},
{x:16562,y:-24732,type:3, level:0, icon:"lm_continent.png", name:{en:"Dyron Stables",fr:"Etables de Dyron",de:"Dyron Ställe",ru:"Стойла Дайрона"}},
{x:19513,y:-26143,type:3, level:0, icon:"lm_continent.png", name:{en:"Thesos Stables",fr:"Etables de Thesos",de:"Thesos Ställe",ru:"Стойла Фессоса"}},
{x:4715,y:-3220,type:3, level:0, icon:"lm_continent.png", name:{en:"Yrkanis Stables",fr:"Etables d&#039;Yrkanis",de:"Stall",ru:"Стойла Мектубов Ирканиса"}},
{x:3808,y:-3745,type:3, level:0, icon:"lm_continent.png", name:{en:"Natae Stables",fr:"Etables de Natae",de:"Natae Ställe",ru:"Стойла Нэтея"}},
{x:4248,y:-4195,type:3, level:0, icon:"lm_continent.png", name:{en:"Davae Stables",fr:"Etables de Davae",de:"Davae Ställe",ru:"Стойла Дэвея"}},
{x:4867,y:-4367,type:3, level:0, icon:"lm_continent.png", name:{en:"Avalae Stables",fr:"Etables d&#039;Avalae",de:"Avalae Ställe",ru:"Стойла Эвелея"}},
{x:15657,y:-33002,type:3, level:0, icon:"lm_continent.png", name:{en:"Windermeer Stables",fr:"Etables de Windermeer",de:"Windermeer Ställe",ru:"Стойла Виндермеера"}},
{x:17260,y:-32937,type:3, level:0, icon:"lm_continent.png", name:{en:"Fairhaven Stables",fr:"Etables de Fairhaven",de:"Fairhaven Ställe",ru:"Стойла Фэрхевена"}},
{x:17925,y:-31995,type:3, level:0, icon:"lm_continent.png", name:{en:"Crystabell Stables",fr:"Etables de Crystabell",de:"Crystabell Ställe",ru:"Стойла Кристабелла"}},
{x:18186,y:-31097,type:3, level:0, icon:"lm_continent.png", name:{en:"Avendale Stables",fr:"Etables d&#039;Avendale",de:"Avendale Ställe",ru:"Стойла Эвендейла"}},
{x:8732,y:-2987,type:3, level:0, icon:"lm_continent.png", name:{en:"Zora Stables",fr:"Etables de Zora",de:"Stall",ru:"Стойла Мектубов Зоры"}},
{x:9546,y:-3633,type:3, level:0, icon:"lm_continent.png", name:{en:"Hoï-Cho Stables",fr:"Etables d&#039;Hoi Cho",de:"Hoi-Cho-Ställe",ru:"Стойла Хоа Шо"}},
{x:8699,y:-3735,type:3, level:0, icon:"lm_continent.png", name:{en:"Jen-Laï Stables",fr:"Etables de Jen Lai",de:"Jen-Lai-Ställe",ru:"Стойла Джен Лай"}},
{x:9822,y:-4261,type:3, level:0, icon:"lm_continent.png", name:{en:"Min-Cho Stables",fr:"Etables de Min Cho",de:"Min-Cho-Ställe",ru:"Стойла Мин Хо"}},
{x:887,y:-10316,type:2, level:0, icon:"lm_continent.png", name:{en:"West Saprun Research Center",fr:"Centre de Recherche de la Montée de Sève Ouest",de:"Forschungszentrum der Westlichen Sapquelle",ru:"Исследовательский центр западного Сэпотока"}},
{x:1201,y:-10477,type:2, level:0, icon:"lm_continent.png", name:{en:"East Saprun Workshop",fr:"Atelier de la Montée de Sève Est",de:"Werkstatt der Östlichen Sapquelle",ru:"Мастерская восточного Сэпотока"}},
{x:702,y:-10800,type:2, level:0, icon:"lm_continent.png", name:{en:"Nexusgate Stronghold",fr:"Forteresse de la Porte du Nexus",de:"Festung der Nexuspforte",ru:"Форт Врата Нексуса"}},
{x:18313,y:-25333,type:2, level:0, icon:"lm_continent.png", name:{en:"Blackburn Trade Post",fr:"Poste d&#039;Echange de la Combustion",de:"Schwarzbrand-Handelsposten",ru:"Фактория Кострище"}},
{x:17672,y:-24559,type:2, level:0, icon:"lm_continent.png", name:{en:"Northlake Farm",fr:"Ferme du Lac du Nord",de:"Hof am Nördlichen See",ru:"Ферма у Северного Озера"}},
{x:17993,y:-24585,type:2, level:0, icon:"lm_continent.png", name:{en:"Northlake Trade Post",fr:"Poste d&#039;Echange du Lac du Nord",de:"Handelsposten am Nördlichen See",ru:"Фактория у Севеерного Озера"}},
{x:18007,y:-25043,type:2, level:0, icon:"lm_continent.png", name:{en:"Barkgully Workshop",fr:"Atelier du Couloir aux Ecorces",de:"Rindenspalt-Werkstatt",ru:"Мастерская Корковражье"}},
{x:17490,y:-25682,type:2, level:0, icon:"lm_continent.png", name:{en:"West Blackburn Border Post",fr:"Poste Frontière Ouest de la Combustion",de:"West-Schwarzbrand-Grenzposten",ru:"Пограничная застава Западное Кострище"}},
{x:16906,y:-24707,type:2, level:0, icon:"lm_continent.png", name:{en:"East Dyron Workshop",fr:"Atelier de Dyron Est",de:"Dyron-Ost-Werkstatt",ru:"Мастерская Восточный Дайрон"}},
{x:17186,y:-25388,type:2, level:0, icon:"lm_continent.png", name:{en:"Frahar Towers Border Post",fr:"Poste Frontière des Tours de Frahar",de:"Frahar-Türme-Grenzposten",ru:"Пограничная застава Башни Фрахар"}},
{x:17047,y:-25682,type:2, level:0, icon:"lm_continent.png", name:{en:"Hightowers Stronghold",fr:"Forteresse des Hautes Tours",de:"Hochtürme-Festung",ru:"Форт Высоких Башен"}},
{x:16720,y:-25860,type:2, level:0, icon:"lm_continent.png", name:{en:"Hightowers Farm",fr:"Ferme des Hautes Tours",de:"Hochtürme-Hof",ru:"Ферма Высоких Башен"}},
{x:20082,y:-24864,type:2, level:0, icon:"lm_continent.png", name:{en:"Barker Canyon Stronghold",fr:"Forteresse du Canyon de Barker",de:"Rindenschlucht-Festung",ru:"Форт Каньона Искусников "}},
{x:19607,y:-25221,type:2, level:0, icon:"lm_continent.png", name:{en:"Barker Canyon Farm",fr:"Ferme du Canyon de Barker",de:"Rindenschlucht-Hof",ru:"Ферма Каньона Искусников"}},
{x:19606,y:-25532,type:2, level:0, icon:"lm_continent.png", name:{en:"Highridges Diplomatic Outpost",fr:"Avant-Poste Diplomatique des Hauts Récifs",de:"Diplomatischer Außenposten des Hohen Riffs",ru:"Дипломатическая миссия Вышние Хребты"}},
{x:19273,y:-25851,type:2, level:0, icon:"lm_continent.png", name:{en:"Workshop of the Waste ",fr:"Atelier des Terres Désolées",de:"Werkstatt des Untergangs",ru:"Мастерская Пустоши"}},
{x:19748,y:-25997,type:2, level:0, icon:"lm_continent.png", name:{en:"Thesos Research Center",fr:"Centre de Recherche de Thesos",de:"Thesos-Forschungszentrum",ru:"Исследовательский центр Фессоса"}},
{x:16272,y:-24253,type:2, level:0, icon:"lm_continent.png", name:{en:"Dyron Hill Border Post",fr:"Poste Frontière de la Colline de Dyron",de:"Grenzposten der Dyron-Anhöhe",ru:"Пограничная Застава Холм Дайрона"}},
{x:16702,y:-24264,type:2, level:0, icon:"lm_continent.png", name:{en:"North Dyron Stronghold",fr:"Forteresse de Dyron Nord",de:"Norddyron-Festung",ru:"Форт Северный Дайрон"}},
{x:16092,y:-24713,type:2, level:0, icon:"lm_continent.png", name:{en:"Dragon&#039;s Tail Workshop",fr:"Atelier de la Queue du Dragon",de:"Drachenschwanz-Werkstatt",ru:"Мастерская Хвост Дракона"}},
{x:16374,y:-25334,type:2, level:0, icon:"lm_continent.png", name:{en:"Malmont Farm",fr:"Ferme de Malmontagne",de:"Malmont-Hof",ru:"Ферма Мальмонт"}},
{x:16382,y:-25812,type:2, level:0, icon:"lm_continent.png", name:{en:"Canyon Road Workshop",fr:"Atelier de la Route du Canyon",de:"Canyonweg-Werkstatt",ru:"Мастерская дороги Каньонов"}},
{x:18955,y:-26157,type:2, level:0, icon:"lm_continent.png", name:{en:"Thesos Springs Stronghold",fr:"Forteresse des Sources de Thesos",de:"Festung der Thesos-Quelle",ru:"Форт Родники Фессоса"}},
{x:20070,y:-26463,type:2, level:0, icon:"lm_continent.png", name:{en:"Running Ridge Workshop",fr:"Atelier de la Crête Eternelle",de:"Werkstatt am Langen Grat",ru:"Мастерская Бегущей Гряды"}},
{x:19104,y:-26637,type:2, level:0, icon:"lm_continent.png", name:{en:"South Range Diplomatic Outpost",fr:"Avant-Poste Diplomatique de la Chaîne Sud",de:"Diplomatischer Außenposten der Südlichen Hügelkette",ru:"Дипломатическая Миссия южного Предела"}},
{x:18312,y:-26805,type:2, level:0, icon:"lm_continent.png", name:{en:"Southend Dune Farm",fr:"Ferme des Dunes du Bas",de:"Hof der Entlegenen Dünen",ru:"Ферма Южные дюны"}},
{x:19933,y:-26823,type:2, level:0, icon:"lm_continent.png", name:{en:"Kipucka Plain Border Post",fr:"Poste Frontière de la Plaine des Kipuckas",de:"Grenzposten der Kipucka-Ebene",ru:"Пограничная Застава Равнин Кипакка"}},
{x:19134,y:-25195,type:2, level:0, icon:"lm_continent.png", name:{en:"Dragon&#039;s Spine Stronghold",fr:"Forteresse de la Colonne du Dragon",de:"Stachel-des-Drachen-Festung",ru:"Форт Драконий Хребет"}},
{x:18936,y:-25680,type:2, level:0, icon:"lm_continent.png", name:{en:"Dragon&#039;s Spine Workshop",fr:"Atelier de la Colonne du Dragon",de:"Stachel-des-Drachen-Werkstatt",ru:"Мастерская Драконий Хребет"}},
{x:18185,y:-25671,type:2, level:0, icon:"lm_continent.png", name:{en:"Woodburn Magic Pole",fr:"Pôle Magique des Bois Calcifiés",de:"Holzbrand - Magischer Ort",ru:"Очаг магии Пылающее древо"}},
{x:17848,y:-25828,type:2, level:0, icon:"lm_continent.png", name:{en:"Woodburn Stronghold",fr:"Forteresse des Bois Calcifiés",de:"Holzbrand-Festung",ru:"Форт У пылающего древа"}},
{x:4247,y:-715,type:2, level:0, icon:"lm_continent.png", name:{en:"Westgrove Stronghold",fr:"Forteresse du Bosquet Ouest",de:"Westwald-Festung",ru:"Форт Западной Рощи"}},
{x:4557,y:-556,type:2, level:0, icon:"lm_continent.png", name:{en:"Eastgrove Workshop",fr:"Atelier du Bosquet Est",de:"Ostwald-Werkstatt",ru:"Мастерская Восточной Рощи"}},
{x:5035,y:-884,type:2, level:0, icon:"lm_continent.png", name:{en:"Highgrove Research Center",fr:"Centre de Recherche du Bosquet Supérieur",de:"Hochwald-Forschungszentrum",ru:"Исследовательский центр Вышней Рощи"}},
{x:4880,y:-1200,type:2, level:0, icon:"lm_continent.png", name:{en:"Ginti Workshop",fr:"Atelier de Ginti",de:"Ginti-Werkstatt",ru:"Лаборатория Джинти"}},
{x:1690,y:-1832,type:2, level:0, icon:"lm_continent.png", name:{en:"Little Mountain Workshop",fr:"Atelier de la Petite Montagne",de:"Werkstatt des Kleinen Berges",ru:"Мастерская у Маленькой Горы"}},
{x:2151,y:-1525,type:2, level:0, icon:"lm_continent.png", name:{en:"Little Mountain Stronghold",fr:"Forteresse de la Petite Montagne",de:"Festung des Kleinen Berges",ru:"Форт у Маленькой Горы"}},
{x:1519,y:-1354,type:2, level:0, icon:"lm_continent.png", name:{en:"Berello Gorge Border Post",fr:"Poste Frontière de la Gorge de Berello",de:"Berello-Schlucht-Grenzposten",ru:"Пограничная застава Ущелье Берелло"}},
{x:1673,y:-892,type:2, level:0, icon:"lm_continent.png", name:{en:"Virginia Falls Diplomatic Outpost",fr:"Avant-Poste Diplomatique des Chutes de Virginia",de:"Diplomatischer Außenposten der Virginia-Fälle",ru:"Дипломатическая Миссия Водопад Виргиния"}},
{x:1364,y:-568,type:2, level:0, icon:"lm_continent.png", name:{en:"Virginia Falls Magic Pole",fr:"Pôle Magique des Chutes de Virginia",de:"Magischer Ort der Virginia-Fälle",ru:"Очаг Магии Водопад Виргиния"}},
{x:5357,y:-6481,type:2, level:0, icon:"lm_continent.png", name:{en:"Upper Hovel Diplomatic Outpost",fr:"Avant-Poste Diplomatique de la Masure Supérieure",de:"Diplomatischer Außenposten der Oberen Hütte",ru:"Дипломатическая Миссия верхнего Логова"}},
{x:5039,y:-6797,type:2, level:0, icon:"lm_continent.png", name:{en:"Folly Farm",fr:"Ferme de la Folie",de:"Hof der Ebene der Torheit",ru:"Ферма Недомыслия"}},
{x:5360,y:-7126,type:2, level:0, icon:"lm_continent.png", name:{en:"Greenpool Workshop",fr:"Atelier de la Mare Verte",de:"Werkstatt des Grünen Beckens",ru:"Мастерская Зеленый Пруд"}},
{x:5676,y:-7282,type:2, level:0, icon:"lm_continent.png", name:{en:"Chilling Swamp Research Center",fr:"Centre de Recherche du Marais Pétrifiant",de:"Forschungszentrum am Sumpf der Angst",ru:"Исследовательский Центр Знобкого Болота"}},
{x:5515,y:-7596,type:2, level:0, icon:"lm_continent.png", name:{en:"Maze of Sprite Border Post",fr:"Poste Frontière du Labyrinthe des Lutins",de:"Geisterlabyrinth-Grenzposten",ru:"Пограничная застава Лабиринта Спрайтов"}},
{x:3920,y:-6639,type:2, level:0, icon:"lm_continent.png", name:{en:"Panting Pass Research Center",fr:"Centre de Recherche du Col des Palpitations",de:"Forschungszentrum am Schwierigen Pfad",ru:"Исследовательский Центр Удушливого Перевала"}},
{x:3601,y:-6159,type:2, level:0, icon:"lm_continent.png", name:{en:"Stalia Stronghold",fr:"Forteresse de Stalia",de:"Stalia-Festung",ru:"Форт Сталия"}},
{x:4226,y:-5666,type:2, level:0, icon:"lm_continent.png", name:{en:"Fearing  Fen Farm",fr:"Ferme du Marécage de l&#039;Angoisse",de:"Hof am Gefürchteten Sumpf",ru:"Ферма Болото Страха"}},
{x:3929,y:-5504,type:2, level:0, icon:"lm_continent.png", name:{en:"Fencoomb Workshop",fr:"Atelier de Fencoomb",de:"Moorteiche-Werkstatt",ru:"Мастерская у Волглого Лога"}},
{x:2946,y:-2313,type:2, level:0, icon:"lm_continent.png", name:{en:"Runninghill Border Post",fr:"Poste Frontière du Col Vallonné",de:"Gebirgspass-Grenzposten",ru:"Застава Бегущего Холма"}},
{x:2339,y:-2498,type:2, level:0, icon:"lm_continent.png", name:{en:"Wooky Workshop",fr:"Atelier du Réveil",de:"Wooky-Werkstatt",ru:"Мастерская Вуки"}},
{x:2008,y:-2012,type:2, level:0, icon:"lm_continent.png", name:{en:"Dryland Gate Stronghold",fr:"Forteresse de la Porte des Terres Arides",de:"Festung der Ödlandpforte",ru:"Форт Врата Суши"}},
{x:2628,y:-2014,type:2, level:0, icon:"lm_continent.png", name:{en:"Runninghill Research Center",fr:"Centre de Recherche du Col Vallonné",de:"Gebirgspass-Forschungszentrum",ru:"Исследовательский центр Бегущего Холма"}},
{x:2488,y:-1506,type:2, level:0, icon:"lm_continent.png", name:{en:"Ryecliff Stronghold",fr:"Forteresse de la Falaise de Rye",de:"Festung der Klippe von Rye",ru:"Форт Ржаного Мыса"}},
{x:2976,y:-1514,type:2, level:0, icon:"lm_continent.png", name:{en:"Torbak Hill Farm",fr:"Ferme de la Colline des Torbaks",de:"Hof der Anhöhe der Torbaks",ru:"Фирма Холма Торбаков"}},
{x:3587,y:-1694,type:2, level:0, icon:"lm_continent.png", name:{en:"Smitten Mount Workshop",fr:"Atelier de la Montagne du Tourment",de:"Werkstatt am Berg der Pein",ru:"Мастерская Обрушенной горы"}},
{x:3611,y:-2011,type:2, level:0, icon:"lm_continent.png", name:{en:"Smitten Mount Farm",fr:"Ferme de la Montagne du Tourment",de:"Hof am Berg der Pein",ru:"Ферма Обрушенной Горы"}},
{x:3292,y:-2790,type:2, level:0, icon:"lm_continent.png", name:{en:"Psykopla Knoll Trading Post",fr:"Poste d&#039;Echange du Monticule des Psykoplas",de:"Handelsposten am Psykopla-Hügel",ru:"Фактория Холмы Псикоплы "}},
{x:4254,y:-5032,type:2, level:0, icon:"lm_continent.png", name:{en:"The Rising Border Post",fr:"Poste Frontière de la Poussée",de:"Grenzposten der Erhebung",ru:"Пограничная застава На Возвышенности"}},
{x:4710,y:-5189,type:2, level:0, icon:"lm_continent.png", name:{en:"Southeast Trade Post",fr:"Poste d&#039;Echange du Sud-Est",de:"Südöstlicher Handelsposten",ru:"Фактория Юго-Восточная"}},
{x:5029,y:-5533,type:2, level:0, icon:"lm_continent.png", name:{en:"Finder&#039;s Farm",fr:"Ferme de l&#039;Inventeur",de:"Hof des Entdeckers",ru:"Ферма Первооткрывателей"}},
{x:5223,y:-5850,type:2, level:0, icon:"lm_continent.png", name:{en:"Trove Workshop",fr:"Atelier du Trésor",de:"Werkstatt des Horts",ru:"Мастерская Сокровищницы"}},
{x:5831,y:-6146,type:2, level:0, icon:"lm_continent.png", name:{en:"Kami Circle Magic Pole",fr:"Pôle Magique du Cercle Kamic",de:"Magischer Ort des Kami-Kreises",ru:"Магический Очаг круга Ками"}},
{x:9213,y:-6464,type:2, level:0, icon:"lm_continent.png", name:{en:"Ichorgate Research Center",fr:"Centre de Recherche de la Porte d&#039;Ichor",de:"Tor von Ichor - Forschungszentrum",ru:"Исследовательский центр Врата Ихора"}},
{x:8550,y:-6815,type:2, level:0, icon:"lm_continent.png", name:{en:"Hammer Hills Trade Post",fr:"Poste d&#039;Echange des Collines Martelées",de:"Hammerhöhen-Handelsposten",ru:"Фактория Холмы-Молоты"}},
{x:8250,y:-7113,type:2, level:0, icon:"lm_continent.png", name:{en:"Umbragate Farm",fr:"Ferme de la Porte des Ombres",de:"Tor nach Umbra - Hof",ru:"Ферма Врата Тени"}},
{x:9529,y:-7128,type:2, level:0, icon:"lm_continent.png", name:{en:"Destiny&#039;s End Diplomatic Outpost",fr:"Avant-Poste Diplomatique de la Fin de la Destinée",de:"Schicksalsende - Diplomatischer Außenposten",ru:"Дипломатическая миссия Роковой предел"}},
{x:9034,y:-7293,type:2, level:0, icon:"lm_continent.png", name:{en:"Watchcomb Workshop",fr:"Atelier de Gardecombe",de:"Talwacht-Werkstatt",ru:"Мастерская Гребень Наблюдателей"}},
{x:8541,y:-7426,type:2, level:0, icon:"lm_continent.png", name:{en:"Highwatch Farm",fr:"Ferme de la Crête Surveillée",de:"Hohe Wacht - Hof",ru:"Ферма Высшее Наблюдение"}},
{x:8867,y:-7773,type:2, level:0, icon:"lm_continent.png", name:{en:"Wastegate Border Post",fr:"Poste Frontière de la Porte des Terres Désolées",de:"Tor ins Niemandsland – Grenzposten",ru:"Пограничная застава Врата Пустоши"}},
{x:5998,y:-9845,type:2, level:0, icon:"lm_continent.png", name:{en:"Ruins of Leron Workshop",fr:"Atelier des Ruines de Léron",de:"Werkstatt der Ruinen von Leron",ru:"Мастерская Руин Лернона"}},
{x:6006,y:-10799,type:2, level:0, icon:"lm_continent.png", name:{en:"Halls of Darkring Research Center",fr:"Centre de Recherche des Salles de la Bague Noire",de:"Forschungszentrum der Hallen des Schwarzen Rings",ru:"Исследовательский центр Залы темного кольца "}},
{x:6171,y:-11600,type:2, level:0, icon:"lm_continent.png", name:{en:"The Fallen Tree Workshop",fr:"Atelier de l&#039;Arbre Abattu",de:"Gefallener-Baum-Werkstatt",ru:"Мастерская Падшего Древа"}},
{x:5838,y:-12232,type:2, level:0, icon:"lm_continent.png", name:{en:"Land of Plenty Research Center",fr:"Centre de Recherche de la Terre d&#039;Abondance",de:"Land des Überflusses - Forschungszentrum",ru:"Исследовательский центр Земли изобилия"}},
{x:6804,y:-12562,type:2, level:0, icon:"lm_continent.png", name:{en:"Underwood Woe Stronghold",fr:"Forteresse des Sous-Bois du Malheur",de:"Festung am Unterholz des Unglücks",ru:"Форт Горе Подлесное"}},
{x:6021,y:-13063,type:2, level:0, icon:"lm_continent.png", name:{en:"Three Totems Pass Workshop",fr:"Atelier du Col des Trois Totems",de:"Dreitotempass-Werkstatt",ru:"Мастерская Проход трех Тотемов"}},
{x:6482,y:-13679,type:2, level:0, icon:"lm_continent.png", name:{en:"Alleyways Bluff Stronghold",fr:"Forteresse de la Ruelle",de:"Festung des Klippendurchgangs",ru:"Форт Утеса трех переулков"}},
{x:6326,y:-13999,type:2, level:0, icon:"lm_continent.png", name:{en:"High Henge Research Center",fr:"Centre de Recherche du Cromlech Supérieur",de:"Forschungszentrum des Oberen Steinkreises",ru:"Исследовательский центр Высокие Мезолиты "}},
{x:6635,y:-14654,type:2, level:0, icon:"lm_continent.png", name:{en:"Lowhills Stronghold",fr:"Forteresse des Basses Collines",de:"Festung der Kleinen Hügel",ru:"Форт Малохолмья"}},
{x:6318,y:-15289,type:2, level:0, icon:"lm_continent.png", name:{en:"Lowhills Research Center",fr:"Centre de Recherche des Basses Collines",de:"Forschungszentrum der Kleinen Hügel",ru:"Исследовательский центр Малохолмья"}},
{x:6138,y:-16217,type:2, level:0, icon:"lm_continent.png", name:{en:"Eerie Valley Magic Pole",fr:"Pôle Magique de la Vallée Sinistre",de:"Schauriges Tal - Magischer Ort",ru:"Очаг Магии Долина Ужаса"}},
{x:6799,y:-16398,type:2, level:0, icon:"lm_continent.png", name:{en:"Aedengate Workshop",fr:"Atelier de la Porte d&#039;Aeden",de:"Aedenpforte-Werkstatt",ru:"Мастерская Врата Аэдан"}},
{x:5678,y:-16719,type:2, level:0, icon:"lm_continent.png", name:{en:"Yelkgrove Border Post",fr:"Poste Frontière du Bosquet des Yelks",de:"Yelkwäldchen-Grenzposten",ru:"Пограничная застава Роща Йелков"}},
{x:3122,y:-10160,type:2, level:0, icon:"lm_continent.png", name:{en:"Deadtree Stronghold",fr:"Forteresse de l&#039;Arbre Mort",de:"Festung des Toten Baumes",ru:"Форт Мертводрева"}},
{x:3459,y:-10477,type:2, level:0, icon:"lm_continent.png", name:{en:"Sap Marsh Trade Post",fr:"Poste d&#039;Echange du Marécage de la Sève",de:"Sapsumpf-Handelsposten",ru:"Фактория Болота Сэп"}},
{x:2958,y:-10799,type:2, level:0, icon:"lm_continent.png", name:{en:"Shooting Meadow Border Post",fr:"Poste Frontière du Pré Lancinant",de:"Grenzposten der Stechenden Wiese",ru:"Пограничная застава Луг Застрельщиков"}},
{x:551,y:-13516,type:2, level:0, icon:"lm_continent.png", name:{en:"Grotto Walk Research Center",fr:"Centre de Recherche de la Promenade des Grottes",de:"Grottenweg-Forschungszentrum",ru:"Исследовательский центр Тропа Грота"}},
{x:1345,y:-13836,type:2, level:0, icon:"lm_continent.png", name:{en:"Cursed Cavern Stronghold",fr:"Forteresse de la Caverne Maudite",de:"Festung der Verfluchten Höhle",ru:"Форт Проклятой Пещеры"}},
{x:876,y:-13999,type:2, level:0, icon:"lm_continent.png", name:{en:"Great Mushroom Wood Workshop",fr:"Atelier des Bois du Champignon Géant",de:"Werkstatt im Großen Pilzwald",ru:"Мастерская Великого Грибного Леса"}},
{x:1039,y:-14473,type:2, level:0, icon:"lm_continent.png", name:{en:"Wings of Spite Farm",fr:"Ferme des Ailes du Dépit",de:"Hof des Flügels der Feindschaft",ru:"Ферма Крылья Досады"}},
{x:1041,y:-14801,type:2, level:0, icon:"lm_continent.png", name:{en:"Continuity Corner Diplomatic Outpost",fr:"Avant-Poste Diplomatique du Tournant de la Continuité",de:"Diplomatischer Außenposten in der Wegkehre der Kontinuität",ru:"Дипломатическая миссия Точка непрерывности"}},
{x:1840,y:-13520,type:2, level:0, icon:"lm_continent.png", name:{en:"Saplake Major Stronghold",fr:"Forteresse du Lac Majeure de Sève",de:"Festung des Großen Sapsees",ru:"Форт Большое Сэпозеро"}},
{x:2316,y:-13680,type:2, level:0, icon:"lm_continent.png", name:{en:"Stockdell  Workshop",fr:"Atelier du Valon des Souches",de:"Werkstatt im Freundlichen Tal",ru:"Мастерская Стокделл"}},
{x:2656,y:-14323,type:2, level:0, icon:"lm_continent.png", name:{en:"Haunted Gorge Farm",fr:"Ferme de la Gorge Hantée",de:"Hof an der Schlucht des Spuks",ru:"Мастерская ущелья Призраков"}},
{x:2326,y:-14801,type:2, level:0, icon:"lm_continent.png", name:{en:"Dragon Horns Workshop",fr:"Atelier des Cornes du Dragon",de:"Drachenhorn-Werkstatt",ru:"Мастерская драконова Рога"}},
{x:1545,y:-15099,type:2, level:0, icon:"lm_continent.png", name:{en:"Ruins of Cryton Farm",fr:"Ferme des Ruines de Cryton",de:"Hof der Ruinen von Cryton",ru:"Ферма Руины Крайтона"}},
{x:2633,y:-15285,type:2, level:0, icon:"lm_continent.png", name:{en:"Hall of the Mountain Bane Stronghold",fr:"Forteresse de la Salle de la Montagne Empoisonnée",de:"Festung des vergifteten Berges",ru:"Форт залов горного Бедствия"}},
{x:18967,y:-29845,type:2, level:0, icon:"lm_continent.png", name:{en:"Watergate Border Post",fr:"Poste Frontière de la Porte des Eaux",de:"Wasserpforte-Grenzposten",ru:"Пограничная застава Врата Вод"}},
{x:17519,y:-29999,type:2, level:0, icon:"lm_continent.png", name:{en:"Loria Stronghold",fr:"Forteresse de Loria",de:"Lorias Festung",ru:"Форт Лории"}},
{x:19601,y:-30320,type:2, level:0, icon:"lm_continent.png", name:{en:"Loria Ponds Research Center",fr:"Centre de Recherche des Etangs de Loria",de:"Lorias Teiche - Forschungszentrum",ru:"Исследовательский центр Пруды Лории "}},
{x:19112,y:-30641,type:2, level:0, icon:"lm_continent.png", name:{en:"Whirling Stronghold",fr:"Forteresse du Tourbillon",de:"Wirbelwind-Festung",ru:"Форт Ветряки"}},
{x:19281,y:-31438,type:2, level:0, icon:"lm_continent.png", name:{en:"Gusty Gorge Workshop",fr:"Atelier de la Gorge des Vents",de:"Werkstatt der Stürmischen Schlucht",ru:"Мастерская Теснины Ветров"}},
{x:16572,y:-30004,type:2, level:0, icon:"lm_continent.png", name:{en:"Loriagate Border Post",fr:"Poste d&#039;Echange de Port-Loria",de:"Grenzposten des Tors von Loria",ru:"Пограничная застава Врата Лории"}},
{x:15764,y:-30321,type:2, level:0, icon:"lm_continent.png", name:{en:"Windyway Workshop",fr:"Atelier de la Route des Vents",de:"Weg der Winde - Werkstatt",ru:"Мастерская Дороги Ветров"}},
{x:15104,y:-30642,type:2, level:0, icon:"lm_continent.png", name:{en:"Muse Watch Lake Farm",fr:"Ferme du Lac des Veilleurs de Songe",de:"Hof am See der Traumwächter",ru:"Ферма Стражи озера Муз"}},
{x:16410,y:-30643,type:2, level:0, icon:"lm_continent.png", name:{en:"Threepillars Farm",fr:"Ferme de la Tricolonne",de:"Drei-Säulen-Hof",ru:"Ферма Три Опоры"}},
{x:15601,y:-31121,type:2, level:0, icon:"lm_continent.png", name:{en:"Musemere Workshop",fr:"Atelier de l&#039;Etang de la Contemplation",de:"Werkstatt der Verträumten Seen",ru:"Мастерская Озеро Муз"}},
{x:14483,y:-31760,type:2, level:0, icon:"lm_continent.png", name:{en:"Cute Springs Research Center",fr:"Centre de Recherche des Sources des Cutes",de:"Cute-Quellsee-Forschungszentrum",ru:"Исследовательский Центр Ключи Кьют"}},
{x:14961,y:-31762,type:2, level:0, icon:"lm_continent.png", name:{en:"Liberty Gateway Border Post",fr:"Poste Frontière de la Porte de la Liberté",de:"Grenzposten des Tors zur Freiheit",ru:"Пограничная застава Врата Вольности"}},
{x:14322,y:-32240,type:2, level:0, icon:"lm_continent.png", name:{en:"Cute Springs Twining Stronghold",fr:"Forteresse des Sources Agitées des Cutes",de:"Festung der Sprudelnden Cute-Quellen",ru:"Форт плетения Кьют"}},
{x:14148,y:-32720,type:2, level:0, icon:"lm_continent.png", name:{en:"Tupile Trade Post",fr:"Poste d&#039;Echange de Tupile",de:"Tupile-Handelsposten",ru:"Фактория Тьюпайл"}},
{x:14961,y:-32719,type:2, level:0, icon:"lm_continent.png", name:{en:"Twintops Workshop",fr:"Atelier des Cimes Jumelles",de:"Zwillingsgipfel-Werkstatt",ru:"Мастерская Пики Близнецы"}},
{x:14799,y:-33680,type:2, level:0, icon:"lm_continent.png", name:{en:"Fount Lake Workshop",fr:"Atelier du Lac des Sources",de:"Quellsee-Werkstatt",ru:"Мастерская Озеро Родника"}},
{x:14626,y:-34159,type:2, level:0, icon:"lm_continent.png", name:{en:"Bountygate Border Post",fr:"Poste Frontière de la Porte de la Générosité",de:"Grenzposten am Tor des Überflusses",ru:"Пограничная застава Врата Изобилия"}},
{x:15280,y:-34157,type:2, level:0, icon:"lm_continent.png", name:{en:"Fount Porch Trade Post",fr:"Poste d&#039;Echange du Porche des Sources",de:"Quellhalle-Handelsposten",ru:"Фактория Террасы Родника"}},
{x:14648,y:-34644,type:2, level:0, icon:"lm_continent.png", name:{en:"Corrie Finley Farm",fr:"Ferme de Corrie Finley",de:"Corrie-Finley-Hof",ru:"Ферма Корри Финли"}},
{x:15770,y:-34641,type:2, level:0, icon:"lm_continent.png", name:{en:"Ponders End Workshop",fr:"Atelier des Colonnes de la Méditation",de:"Werkstatt der Säulen der Besinnung",ru:"Мастерская Предел раздумий"}},
{x:18322,y:-33679,type:2, level:0, icon:"lm_continent.png", name:{en:"Tippy Peaks Diplomatic Outpost",fr:"Avant-Poste Diplomatique des Pics Instables",de:"Diplomatischer Außenposten der Brüchigen Gipfel",ru:"Дипломатическая Миссия Острые Пики"}},
{x:17506,y:-34002,type:2, level:0, icon:"lm_continent.png", name:{en:"Sinking Sands Workshop",fr:"Atelier des Sables de la Perdition",de:"Werkstatt des Sinkenden Sandes",ru:"Мастерская Зыбучие пески"}},
{x:18172,y:-34000,type:2, level:0, icon:"lm_continent.png", name:{en:"Eastshore Magic Pole",fr:"Pôle Magique de la Rivest",de:"Magischer Ort der Ostküste",ru:"Очаг Магии Истхорн"}},
{x:17840,y:-34319,type:2, level:0, icon:"lm_continent.png", name:{en:"Graveyard Gate Research Center",fr:"Centre de Recherche de la Promenade Caverneuse",de:"Friedhofspforte-Forschungszentrum",ru:"Исследовательский центр У кладбищенских врат "}},
{x:17361,y:-34476,type:2, level:0, icon:"lm_continent.png", name:{en:"Mire of the Dire Stronghold",fr:"Forteresse du Bourbier de la Misère",de:"Festung des Grässlichen Morasts",ru:"Форт Зловещая Трясина"}},
{x:15911,y:-32245,type:2, level:0, icon:"lm_continent.png", name:{en:"Darkmoor Border Post",fr:"Poste Frontière des Landes Obscures",de:"Schwarzmoor-Grenzposten",ru:"Пограничная застава Мрачные Топи"}},
{x:17993,y:-32407,type:2, level:0, icon:"lm_continent.png", name:{en:"Dainty Isle Workshop",fr:"Atelier de l&#039;Ile de la Fragilité",de:"Werkstatt der Anmutigen Insel",ru:"Мастерская Остров Изящества"}},
{x:16415,y:-32574,type:2, level:0, icon:"lm_continent.png", name:{en:"Sandy Workshop",fr:"Atelier des Sables",de:"Sandy-Werkstatt",ru:"Песчаная Мастерская"}},
{x:17678,y:-32712,type:2, level:0, icon:"lm_continent.png", name:{en:"Farely Farm",fr:"Ferme de Farely",de:"Farely-Hof",ru:"Ферма Фэйрлей"}},
{x:16728,y:-32860,type:2, level:0, icon:"lm_continent.png", name:{en:"Greenvale Trade Post",fr:"Poste d&#039;Echange de Vertval",de:"Grünes Tal - Handelsposten",ru:"Фактория Зеленая Долина"}},
{x:15916,y:-33192,type:2, level:0, icon:"lm_continent.png", name:{en:"Windermeer Farm",fr:"Ferme de Windermeer",de:"Windermeer-Hof",ru:"Ферма Виндермеера"}},
{x:11933,y:-5191,type:2, level:0, icon:"lm_continent.png", name:{en:"Withered Stock Magic Pole",fr:"Pôle Magique de la Souche Flétrie",de:"Magischer Ort des Verdorrten Stammes",ru:"Очаг Магии Заброшенный Кладезь"}},
{x:11267,y:-4868,type:2, level:0, icon:"lm_continent.png", name:{en:"Gu-Qin Workshop",fr:"Atelier de Gu-Qin",de:"Gu-Qin-Werkstatt",ru:"Мастерская Гу-Кина ."}},
{x:9996,y:-4878,type:2, level:0, icon:"lm_continent.png", name:{en:"Doomed Maze Farm",fr:"Ferme du Labyrinthe Condamné",de:"Hof des Verdammten Labyrinths",ru:"Ферма Обреченного Лабиринта"}},
{x:10627,y:-4714,type:2, level:0, icon:"lm_continent.png", name:{en:"Underway Arch Stronghold",fr:"Forteresse de l&#039;Arc Caché",de:"Wölbung-Festung",ru:"Форт свода Подземелий"}},
{x:11776,y:-4544,type:2, level:0, icon:"lm_continent.png", name:{en:"Gu-Qin Research Center",fr:"Centre de Recherche de Gu-Qin",de:"Gu-Qin-Forschungszentrum",ru:"Исследовательский Центр Гу-Кина"}},
{x:11112,y:-4230,type:2, level:0, icon:"lm_continent.png", name:{en:"Umbra Highback  Workshop",fr:"Atelier du Dôme des Ombres",de:"Schattenkuppel-Werkstatt",ru:"Мастерская Теневой гряды"}},
{x:10639,y:-4243,type:2, level:0, icon:"lm_continent.png", name:{en:"Sly Lake Crossroads Border Post",fr:"Poste Frontière du Lac Dissimulé",de:"Grenzposten am Verborgenen See",ru:"Пограничная застава перекрестка у Озера Коварства"}},
{x:10317,y:-3759,type:2, level:0, icon:"lm_continent.png", name:{en:"Qai-Du Workshop",fr:"Atelier de Qai-Du",de:"Qai-Du-Werkstatt",ru:"Мастерская Кай-Ду"}},
{x:11761,y:-3921,type:2, level:0, icon:"lm_continent.png", name:{en:"Land&#039;s End Farm",fr:"Ferme du Bout des Terres",de:"Land-Enden-Hof",ru:"Ферма на краю Света"}},
{x:11282,y:-3595,type:2, level:0, icon:"lm_continent.png", name:{en:"Sai-Shun Stronghold",fr:"Forteresse de Sai-Shun",de:"Sai-Shun-Festung",ru:"Форт Саи-Шуна"}},
{x:10789,y:-3452,type:2, level:0, icon:"lm_continent.png", name:{en:"Maiden Pond Workshop",fr:"Atelier de l&#039;Etang Vierge",de:"Jungfernteich-Werkstatt",ru:"Мастерская у Девственного Пруда"}},
{x:10156,y:-3280,type:2, level:0, icon:"lm_continent.png", name:{en:"Bighand Border Post",fr:"Poste Frontière de la Main Géante",de:"Grenzposten der Großen Hand",ru:"Пограничная Застава Тяжелая Рука"}},
{x:11922,y:-3117,type:2, level:0, icon:"lm_continent.png", name:{en:"Great Boulder Workshop",fr:"Atelier du Grand Tunnel Rocailleux",de:"Werkstatt am Großen Brocken",ru:"Мастерская Великой Глыбы"}},
{x:11429,y:-3109,type:2, level:0, icon:"lm_continent.png", name:{en:"Great Boulder Trade Post",fr:"Poste d&#039;Echange du Grand Tunnel Rocailleux",de:"Handelsposten am Großen Brocken",ru:"Фактория Великой Глыбы"}},
{x:11261,y:-2633,type:2, level:0, icon:"lm_continent.png", name:{en:"Zo-Kian Ruins Workshop",fr:"Atelier des Ruines de Zo-Kian",de:"Zo-Kian Ruinen - Werkstatt",ru:"Мастерская Руины Зо-Киан"}},
{x:10632,y:-2650,type:2, level:0, icon:"lm_continent.png", name:{en:"Lost Valley Stronghold",fr:"Forteresse de la Vallée Perdue",de:"Vergessenes Tal - Festung",ru:"Форт Затерянной Долины"}},
{x:11296,y:-2175,type:2, level:0, icon:"lm_continent.png", name:{en:"Paramount Stock Workshop",fr:"Atelier de la Souche Capitale",de:"Aussicht-Werkstatt",ru:"Мастерская Верховный Кладезь"}},
{x:10789,y:-2174,type:2, level:0, icon:"lm_continent.png", name:{en:"Staring Stronghold",fr:"Forteresse de la Contemplation",de:"Festung der Kontemplation",ru:"Форт Бдительность"}},
{x:11767,y:-1847,type:2, level:0, icon:"lm_continent.png", name:{en:"Witherstock Farm",fr:"Ferme de la Souche Flétrie",de:"Hof des Verdorrten Stamms",ru:"Ферма у Заброшенного Кладезя"}},
{x:9688,y:-2948,type:2, level:0, icon:"lm_continent.png", name:{en:"Kincher Arch Border Post",fr:"Poste Frontière de l&#039;Arc des Kinchers",de:"Kincherbogen-Grenzposten",ru:"Пограничная застава арки Кинчеров"}},
{x:9205,y:-2635,type:2, level:0, icon:"lm_continent.png", name:{en:"Fustylake Workshop",fr:"Atelier du Lac Poussiéreux",de:"Werkstatt am Stickenden See",ru:"Мастерская Прогорклого Озера"}},
{x:9838,y:-2479,type:2, level:0, icon:"lm_continent.png", name:{en:"Demon&#039;s Crossroads Diplomatic Outpost",fr:"Avant-Poste Diplomatique du Croisement du Démon",de:"Diplomatischer Außenposten der Dämonenkreuzung",ru:"Дипломатическая миссия Перекресток Демона "}},
{x:9346,y:-2146,type:2, level:0, icon:"lm_continent.png", name:{en:"Bighorn Mountain Farm",fr:"Ferme de la Montagne aux Cornes",de:"Hornberg-Hof",ru:"Ферма у горы Бигхорн"}},
{x:8242,y:-3597,type:2, level:0, icon:"lm_continent.png", name:{en:"Jen-Laï Research Center",fr:"Centre de Recherche de Jen-Laï",de:"Jen-Laï-Forschungszentrum",ru:"Исследовательский центр Джен-Лаи"}},
{x:7907,y:-2953,type:2, level:0, icon:"lm_continent.png", name:{en:"Lonview Stronghold",fr:"Forteresse de l&#039;Horizon",de:"Horizont-Festung",ru:"Форт Одинокого Наблюдателя"}},
{x:7585,y:-2491,type:2, level:0, icon:"lm_continent.png", name:{en:"Stainmoor Stronghold",fr:"Forteresse de la Lande Tachetée",de:"Fleckenmoor-Festung",ru:"Форт Стэйнмура"}},
{x:8232,y:-2309,type:2, level:0, icon:"lm_continent.png", name:{en:"Stainmoor Border Post",fr:"Poste Frontière de la Lande Tachetée",de:"Fleckenmoor-Grenzposten",ru:"Пограничная застава Стэйнмура"}},
{x:7593,y:-1988,type:2, level:0, icon:"lm_continent.png", name:{en:"Desertstock Farm",fr:"Ferme de Désertstock",de:"Hof des Trockenen Stamms",ru:"Ферма Пустынный Кладезь"}},
{x:7109,y:-1994,type:2, level:0, icon:"lm_continent.png", name:{en:"Great Outback Workshop",fr:"Atelier de l&#039;Arrière-Pays",de:"Werkstatt des Großen Buschlandes",ru:"Мастерская Великая Целина "}},
{x:8575,y:-1670,type:2, level:0, icon:"lm_continent.png", name:{en:"Ni-Jing Farm",fr:"Ferme de Ni-Jing",de:"Ni-Jing-Hof",ru:"Ферма Ни-Джинг"}},
{x:16623,y:-24625,type:1, level:0, icon:"", name:{en:"Dyron",fr:"Dyron",de:"Dyron",ru:"Дайрон"}},
{x:19658,y:-26252,type:1, level:0, icon:"", name:{en:"Thesos",fr:"Thesos",de:"Thesos",ru:"Фессос"}},
{x:21207,y:-25527,type:1, level:0, icon:"", name:{en:"Aegus",fr:"Aegus",de:"Aegus",ru:"Аэгус"}},
{x:21983,y:-26169,type:1, level:0, icon:"", name:{en:"Kaemon",fr:"Kaemon",de:"Kaemon",ru:"Каэмон"}},
{x:22478,y:-25525,type:1, level:0, icon:"", name:{en:"Sekovix",fr:"Sekovix",de:"Sekovix",ru:"Сековикс"}},
{x:21515,y:-26643,type:1, level:0, icon:"", name:{en:"Phyxon",fr:"Phyxon",de:"Phyxon",ru:"Фиксон"}},
{x:22797,y:-26643,type:1, level:0, icon:"", name:{en:"Galemus",fr:"Galemus",de:"Galemus",ru:"Галэмус"}},
{x:3729,y:-3758,type:1, level:0, icon:"", name:{en:"Natae",fr:"Natae",de:"Natae",ru:"Нэтей"}},
{x:4231,y:-4110,type:1, level:0, icon:"", name:{en:"Davae",fr:"Davae",de:"Davae",ru:"Дэвей"}},
{x:4887,y:-4413,type:1, level:0, icon:"", name:{en:"Avalae",fr:"Avalae",de:"Avalae",ru:"Эвелей"}},
{x:862,y:-6310,type:1, level:0, icon:"", name:{en:"Stalli",fr:"Stalli",de:"Stalli",ru:"Сталли"}},
{x:1526,y:-6640,type:1, level:0, icon:"", name:{en:"Borea",fr:"Borea",de:"Borea",ru:"Борея"}},
{x:2169,y:-6628,type:1, level:0, icon:"", name:{en:"Nistia",fr:"Nistia",de:"Nistia",ru:"Нистия"}},
{x:1025,y:-6943,type:1, level:0, icon:"", name:{en:"Rosilio",fr:"Rosilio",de:"Rosilio",ru:"Росилио"}},
{x:1818,y:-7115,type:1, level:0, icon:"", name:{en:"Miani",fr:"Miani",de:"Miani",ru:"Миани"}},
{x:18095,y:-31032,type:1, level:0, icon:"", name:{en:"Avendale",fr:"Avendale",de:"Avendale",ru:"Эвендейл"}},
{x:17886,y:-31885,type:1, level:0, icon:"", name:{en:"Crystabell",fr:"Crystabell",de:"Crystabell",ru:"Кристабелл"}},
{x:15566,y:-32967,type:1, level:0, icon:"", name:{en:"Windermeer",fr:"Windermeer",de:"Windermeer",ru:"Виндермеер"}},
{x:21197,y:-33845,type:1, level:0, icon:"", name:{en:"Aubermouth",fr:"Aubermouth",de:"Aubermouth",ru:"Обермаут"}},
{x:22147,y:-33837,type:1, level:0, icon:"", name:{en:"Barkdell",fr:"Barkdell",de:"Barkdell",ru:"Баркделл"}},
{x:22805,y:-33511,type:1, level:0, icon:"", name:{en:"Hobwelly",fr:"Hobwelly",de:"Hobwelly",ru:"Хобвэлли"}},
{x:21354,y:-34632,type:1, level:0, icon:"", name:{en:"Waverton",fr:"Waverton",de:"Waverton",ru:"Уэвертон"}},
{x:22632,y:-34638,type:1, level:0, icon:"", name:{en:"Dingleton",fr:"Dingleton",de:"Dingleton",ru:"Динглтон"}},
{x:9622,y:-3509,type:1, level:0, icon:"", name:{en:"Hoï-Cho",fr:"Hoï-Cho",de:"Hoï-Cho",ru:"Хоа-Шо"}},
{x:8775,y:-3688,type:1, level:0, icon:"", name:{en:"Jen-Laï",fr:"Jen-Laï",de:"Jen-Laï",ru:"Джен-Лаи"}},
{x:9941,y:-4156,type:1, level:0, icon:"", name:{en:"Min-Cho",fr:"Min-Cho",de:"Min-Cho",ru:"Мин-Хо"}},
{x:7284,y:-4395,type:1, level:0, icon:"", name:{en:"Qaï Lo",fr:"Qaï Lo",de:"Qaï Lo",ru:"Квай-Ло"}},
{x:7760,y:-4878,type:1, level:0, icon:"", name:{en:"Sheng Wo",fr:"Sheng Wo",de:"Sheng Wo",ru:"Шенг-Уо"}},
{x:8398,y:-4586,type:1, level:0, icon:"", name:{en:"Nen Xing",fr:"Nen Xing",de:"Nen Xing",ru:"Нен-Ксинг"}},
{x:7442,y:-5359,type:1, level:0, icon:"", name:{en:"Koï Zun",fr:"Koï Zun",de:"Koï Zun",ru:"Кои-Зан"}},
{x:8400,y:-5200,type:1, level:0, icon:"", name:{en:"Yin Piang",fr:"Yin Piang",de:"Yin Piang",ru:"Йин-Панг"}},
{x:1042,y:-10531,type:-1, level:0, icon:"", name:{en:"Abyss of Ichor",fr:"Gouffre d&#039;Ichor",de:"Abgrund von Ichor",ru:"Кровоточащая бездна"}},
{x:18080,y:-25441,type:-1, level:0, icon:"", name:{en:"Burning Desert",fr:"Désert Ardent",de:"Brennende Wüste",ru:"Пылающая Пустыня"}},
{x:18693,y:-24467,type:0, level:0, icon:"", name:{en:"Pyr",fr:"Pyr",de:"Pyr",ru:"Пайр"}},
{x:23523,y:-24385,type:-1, level:0, icon:"", name:{en:"Old Lands",fr:"Terres Anciennes",de:"Alte Lande",ru:"Старые земли"}},
{x:22090,y:-26159,type:-1, level:0, icon:"", name:{en:"Burning Desert",fr:"Désert Ardent",de:"Brennende Wüste",ru:"Пылающая Пустыня"}},
{x:20639,y:-480,type:-1, level:0, icon:"", name:{en:"a building",fr:"bâtiment",de:"ein Gebäude",ru:"здание"}},
{x:2350,y:-16871,type:-1, level:0, icon:"", name:{en:"Kitins&#039; Lair",fr:"Kitinière",de:"Kitin-Nest",ru:"Логово китинов"}},
{x:3242,y:-3880,type:-1, level:0, icon:"", name:{en:"Verdant Heights",fr:"Sommet Verdoyant",de:"Grüne Anhöhen",ru:"Цветущие выси"}},
{x:4712,y:-3443,type:0, level:0, icon:"", name:{en:"Yrkanis",fr:"Yrkanis",de:"Yrkanis",ru:"Ирканис"}},
{x:16378,y:-917,type:-1, level:0, icon:"", name:{en:"Old Lands",fr:"Terres Anciennes",de:"Alte Lande",ru:"Старые земли"}},
{x:1442,y:-6640,type:-1, level:0, icon:"", name:{en:"Matis Island",fr:"Ile Matis",de:"Matis-Insel",ru:"Остров Матис"}},
{x:9428,y:-11083,type:-1, level:0, icon:"", name:{en:"Controlled Lands",fr:"Terres contrôlées",de:"Kontrollierte Lande",ru:"Освоенные Земли"}},
{x:10350,y:-11758,type:0, level:0, icon:"", name:{en:"Ranger camp",fr:"Campement ranger",de:"Ranger-Lager",ru:"Лагерь Рэйнджеров"}},
{x:8788,y:-7196,type:-1, level:0, icon:"", name:{en:"Nexus Minor",fr:"Nexus Mineur",de:"Kleiner Nexus",ru:"Плато Нексус"}},
{x:6323,y:-13203,type:-1, level:0, icon:"", name:{en:"Lands of Umbra",fr:"Route des Ombres",de:"Länder von Umbra",ru:"Земля Теней"}},
{x:3173,y:-10532,type:-1, level:0, icon:"", name:{en:"Under Spring",fr:"Sources Interdites",de:"Verbotene Quellen",ru:"Подземный источник"}},
{x:1592,y:-14475,type:-1, level:0, icon:"", name:{en:"Wastelands",fr:"Terres Abandonnées",de:"Niemandsland",ru:"Пустоземье"}},
{x:16917,y:-32115,type:-1, level:0, icon:"", name:{en:"Aeden Aqueous",fr:"Aeden Aqueous",de:"Aeden Aqueous",ru:"Эден Аквеос"}},
{x:17192,y:-32989,type:0, level:0, icon:"", name:{en:"Fairhaven",fr:"Fairhaven",de:"Fairhaven",ru:"Фэрхевен"}},
{x:24152,y:-30090,type:-1, level:0, icon:"", name:{en:"Old Lands",fr:"Terres Anciennes",de:"Alte Lande",ru:"Стародавние земли"}},
{x:22015,y:-33943,type:-1, level:0, icon:"", name:{en:"Aeden Aqueous",fr:"Aeden Aqueous",de:"Aeden Aqueous",ru:"Эден Аквеос"}},
{x:9711,y:-3127,type:-1, level:0, icon:"", name:{en:"Witherings",fr:"Pays Malade",de:"Verdorrende Lande",ru:"Земли Увядания"}},
{x:8627,y:-2871,type:0, level:0, icon:"", name:{en:"Zora",fr:"Zora",de:"Zora",ru:"Зора"}},
{x:8055,y:-4922,type:-1, level:0, icon:"", name:{en:"Zoraï Island",fr:"Ile Zoraï",de:"Zoraï-Insel",ru:"Остров Зораи"}}
];
