variant = "loose"

[[issues]]
file = "src/Bmsite/Maps/JavascriptApi/JavascriptFactory.php"
code = "invalid-property-assignment-value"
message = "Invalid type for property `$header`: expected `string`, but got `false|string`."
count = 1

[[issues]]
file = "src/Bmsite/Maps/JavascriptApi/JavascriptFactory.php"
code = "invalid-property-assignment-value"
message = "Invalid type for property `$lastModified`: expected `int`, but got `false|int<1750595956, max>`."
count = 1

[[issues]]
file = "src/Bmsite/Maps/JavascriptApi/JavascriptFactory.php"
code = "possibly-false-operand"
message = "Left operand in `>` comparison might be `false` (type `false|int<1750595956, max>`)."
count = 1

[[issues]]
file = "src/Bmsite/Maps/JavascriptApi/JavascriptFactory.php"
code = "possibly-false-operand"
message = "Possibly false right operand used in string concatenation (type `false|string`)."
count = 1

[[issues]]
file = "src/Bmsite/Maps/ResourceLoader.php"
code = "mixed-return-statement"
message = 'Could not infer a precise return type for function `Bmsite\Maps\ResourceLoader::loadJson`. Saw type `mixed`.'
count = 1

[[issues]]
file = "src/Bmsite/Maps/ResourceLoader.php"
code = "possibly-invalid-argument"
message = "Possible argument type mismatch for argument #1 of `json_decode`: expected `string`, but possibly received `bool|string`."
count = 1

[[issues]]
file = "src/Bmsite/Maps/StaticMap/Layer/TileLayer.php"
code = "possibly-false-argument"
message = "Argument #4 of function `imagefill` is possibly `false`, but parameter type `int` does not accept it."
count = 1

[[issues]]
file = "src/Bmsite/Maps/StaticMap/Layer/TileLayer.php"
code = "possibly-false-argument"
message = "Argument #6 of function `imagestring` is possibly `false`, but parameter type `int` does not accept it."
count = 1

[[issues]]
file = "src/Bmsite/Maps/StaticMap/StaticMapGenerator.php"
code = "possibly-null-operand"
message = "Left operand in arithmetic operation might be `null` (type `float|null`)."
count = 2

[[issues]]
file = "src/Bmsite/Maps/StaticMap/StaticMapGenerator.php"
code = "possibly-null-property-access"
message = "Attempting to access a property on a possibly `null` value."
count = 2

[[issues]]
file = "src/Bmsite/Maps/Tiles/SqlTileStorage.php"
code = "invalid-method-access"
message = "Attempting to access a method on a non-object type (`false`)."
count = 5

[[issues]]
file = "src/Bmsite/Maps/Tiles/SqlTileStorage.php"
code = "mixed-argument"
message = "Invalid argument type for argument #1 of `imagecreatefromstring`: expected `string`, but found `truthy-mixed`."
count = 1

[[issues]]
file = "src/Bmsite/Maps/Tiles/SqlTileStorage.php"
code = "mixed-assignment"
message = "Assigning `mixed` type to a variable may lead to unexpected behavior."
count = 1

[[issues]]
file = "src/Bmsite/Maps/Tools/Console/Command/BuildJsonFiles.php"
code = "invalid-argument"
message = 'Invalid argument type for argument #1 of `Ryzom\Sheets\PackedSheetsCollection::get`: expected `string`, but found `int(6)`.'
count = 1

[[issues]]
file = "src/Bmsite/Maps/Tools/Console/Command/BuildJsonFiles.php"
code = "less-specific-argument"
message = '''Argument type mismatch for argument #2 of `Bmsite\Maps\Tools\Console\Command\BuildJsonFiles::filterContLabel`: expected `array<string, array<string, array{'name': string}>>`, but provided type `array<array-key, mixed>` is less specific.'''
count = 1

[[issues]]
file = "src/Bmsite/Maps/Tools/Console/Command/BuildJsonFiles.php"
code = "mixed-argument"
message = 'Invalid argument type for argument #1 of `Bmsite\Maps\Tools\Console\Command\BuildJsonFiles::buildLabels`: expected `array<array-key, Ryzom\Sheets\Client\CContinent>`, but found `mixed`.'
count = 1

[[issues]]
file = "src/Bmsite/Maps/Tools/Console/Command/BuildJsonFiles.php"
code = "mixed-argument"
message = 'Invalid argument type for argument #1 of `Bmsite\Maps\Tools\Console\Command\BuildJsonFiles::buildRegionPolys`: expected `array<array-key, Ryzom\Sheets\Client\CContinent>`, but found `mixed`.'
count = 1

[[issues]]
file = "src/Bmsite/Maps/Tools/Console/Command/BuildJsonFiles.php"
code = "mixed-argument"
message = 'Invalid argument type for argument #1 of `Bmsite\Maps\Tools\Console\Helper\TranslateHelper::load`: expected `string`, but found `mixed`.'
count = 1

[[issues]]
file = "src/Bmsite/Maps/Tools/Console/Command/BuildJsonFiles.php"
code = "mixed-argument"
message = 'Invalid argument type for argument #1 of `Ryzom\Sheets\PackedSheetsLoader::__construct`: expected `string`, but found `mixed`.'
count = 1

[[issues]]
file = "src/Bmsite/Maps/Tools/Console/Command/BuildJsonFiles.php"
code = "mixed-argument"
message = 'Invalid argument type for argument #2 of `Bmsite\Maps\Tools\Console\Command\BuildJsonFiles::buildServerZones`: expected `string`, but found `mixed`.'
count = 1

[[issues]]
file = "src/Bmsite/Maps/Tools/Console/Command/BuildJsonFiles.php"
code = "mixed-argument"
message = 'Invalid argument type for argument #3 of `Bmsite\Maps\Tools\Console\Command\BuildJsonFiles::buildLabels`: expected `string`, but found `mixed`.'
count = 1

[[issues]]
file = "src/Bmsite/Maps/Tools/Console/Command/BuildJsonFiles.php"
code = "mixed-argument"
message = 'Invalid argument type for argument #3 of `Bmsite\Maps\Tools\Console\Command\BuildJsonFiles::buildRegionPolys`: expected `string`, but found `mixed`.'
count = 1

[[issues]]
file = "src/Bmsite/Maps/Tools/Console/Command/BuildJsonFiles.php"
code = "mixed-array-access"
message = "Unsafe array access on type `mixed`."
count = 1

[[issues]]
file = "src/Bmsite/Maps/Tools/Console/Command/BuildJsonFiles.php"
code = "mixed-array-assignment"
message = "Unsafe array assignment on type `mixed`."
count = 1

[[issues]]
file = "src/Bmsite/Maps/Tools/Console/Command/BuildJsonFiles.php"
code = "mixed-assignment"
message = "Assigning `mixed` type to a variable may lead to unexpected behavior."
count = 2

[[issues]]
file = "src/Bmsite/Maps/Tools/Console/Command/BuildJsonFiles.php"
code = "mixed-operand"
message = "Invalid left operand: type `mixed` cannot be reliably used in string concatenation."
count = 3

[[issues]]
file = "src/Bmsite/Maps/Tools/Console/Command/BuildJsonFiles.php"
code = "mixed-operand"
message = "Left operand in binary operation has type `mixed`."
count = 1

[[issues]]
file = "src/Bmsite/Maps/Tools/Console/Command/BuildJsonFiles.php"
code = "null-argument"
message = 'Argument #2 of method `Symfony\Component\Console\Command\Command::addOption` is `null`, but parameter type `string` does not accept it.'
count = 1

[[issues]]
file = "src/Bmsite/Maps/Tools/Console/Command/BuildJsonFiles.php"
code = "redundant-docblock-type"
message = "Redundant docblock type for variable `$sm`."
count = 1

[[issues]]
file = "src/Bmsite/Maps/Tools/Console/Helper/ResourceHelper.php"
code = "mixed-array-access"
message = "Unsafe array access on type `mixed`."
count = 1

[[issues]]
file = "src/Bmsite/Maps/Tools/Console/Helper/ResourceHelper.php"
code = "mixed-array-assignment"
message = "Unsafe array assignment on type `mixed`."
count = 1
