variant = "loose"

[[issues]]
file = "src/Bmsite/Maps/BaseTypes/Polygon.php"
code = "no-alias-function"
message = "Function alias `join` should not be used."
count = 1

[[issues]]
file = "src/Bmsite/Maps/JavascriptApi/JavascriptFactory.php"
code = "no-boolean-flag-parameter"
message = "Avoid boolean flag parameters."
count = 1

[[issues]]
file = "src/Bmsite/Maps/JavascriptApi/JsMinifier.php"
code = "inline-variable-return"
message = "Variable assignment can be inlined into the return statement."
count = 1

[[issues]]
file = "src/Bmsite/Maps/MapProjection.php"
code = "prefer-early-continue"
message = "Consider using early continue pattern to reduce nesting."
count = 4

[[issues]]
file = "src/Bmsite/Maps/MapProjection.php"
code = "use-compound-assignment"
message = "Use a compound assignment for clarity and performance."
count = 2

[[issues]]
file = "src/Bmsite/Maps/StaticMap.php"
code = "no-empty-catch-clause"
message = "Do not use empty `catch` blocks."
count = 1

[[issues]]
file = "src/Bmsite/Maps/StaticMap.php"
code = "str-contains"
message = "Consider replacing `strpos` with `str_contains` for improved readability and intent clarity."
count = 2

[[issues]]
file = "src/Bmsite/Maps/Tiles/SqlTileStorage.php"
code = "file-name"
message = "Class `TileStorage` should be in a file named `TileStorage.php`, found `SqlTileStorage.php`."
count = 1
